// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldID, id))
}

// TicketNo applies equality check predicate on the "ticket_no" field. It's identical to TicketNoEQ.
func TicketNo(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTicketNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserEmail, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserName, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSubject, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCategory, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPriority, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSource, v))
}

// TemplateKey applies equality check predicate on the "template_key" field. It's identical to TemplateKeyEQ.
func TemplateKey(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTemplateKey, v))
}

// ContextType applies equality check predicate on the "context_type" field. It's identical to ContextTypeEQ.
func ContextType(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldContextType, v))
}

// ContextID applies equality check predicate on the "context_id" field. It's identical to ContextIDEQ.
func ContextID(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldContextID, v))
}

// AssigneeID applies equality check predicate on the "assignee_id" field. It's identical to AssigneeIDEQ.
func AssigneeID(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldAssigneeID, v))
}

// EscalatedAt applies equality check predicate on the "escalated_at" field. It's identical to EscalatedAtEQ.
func EscalatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalatedAt, v))
}

// EscalatedBy applies equality check predicate on the "escalated_by" field. It's identical to EscalatedByEQ.
func EscalatedBy(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalatedBy, v))
}

// EscalationReason applies equality check predicate on the "escalation_reason" field. It's identical to EscalationReasonEQ.
func EscalationReason(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalationReason, v))
}

// SLADueAt applies equality check predicate on the "sla_due_at" field. It's identical to SLADueAtEQ.
func SLADueAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSLADueAt, v))
}

// SLARemindedAt applies equality check predicate on the "sla_reminded_at" field. It's identical to SLARemindedAtEQ.
func SLARemindedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSLARemindedAt, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastUserMessageAt applies equality check predicate on the "last_user_message_at" field. It's identical to LastUserMessageAtEQ.
func LastUserMessageAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastUserMessageAt, v))
}

// LastAdminMessageAt applies equality check predicate on the "last_admin_message_at" field. It's identical to LastAdminMessageAtEQ.
func LastAdminMessageAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastAdminMessageAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldResolvedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// TicketNoEQ applies the EQ predicate on the "ticket_no" field.
func TicketNoEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTicketNo, v))
}

// TicketNoNEQ applies the NEQ predicate on the "ticket_no" field.
func TicketNoNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldTicketNo, v))
}

// TicketNoIn applies the In predicate on the "ticket_no" field.
func TicketNoIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldTicketNo, vs...))
}

// TicketNoNotIn applies the NotIn predicate on the "ticket_no" field.
func TicketNoNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldTicketNo, vs...))
}

// TicketNoGT applies the GT predicate on the "ticket_no" field.
func TicketNoGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldTicketNo, v))
}

// TicketNoGTE applies the GTE predicate on the "ticket_no" field.
func TicketNoGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldTicketNo, v))
}

// TicketNoLT applies the LT predicate on the "ticket_no" field.
func TicketNoLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldTicketNo, v))
}

// TicketNoLTE applies the LTE predicate on the "ticket_no" field.
func TicketNoLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldTicketNo, v))
}

// TicketNoContains applies the Contains predicate on the "ticket_no" field.
func TicketNoContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldTicketNo, v))
}

// TicketNoHasPrefix applies the HasPrefix predicate on the "ticket_no" field.
func TicketNoHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldTicketNo, v))
}

// TicketNoHasSuffix applies the HasSuffix predicate on the "ticket_no" field.
func TicketNoHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldTicketNo, v))
}

// TicketNoEqualFold applies the EqualFold predicate on the "ticket_no" field.
func TicketNoEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldTicketNo, v))
}

// TicketNoContainsFold applies the ContainsFold predicate on the "ticket_no" field.
func TicketNoContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldTicketNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUserID, v))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldUserEmail, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldUserName, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldSubject, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldCategory, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldPriority, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldSource, v))
}

// TemplateKeyEQ applies the EQ predicate on the "template_key" field.
func TemplateKeyEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTemplateKey, v))
}

// TemplateKeyNEQ applies the NEQ predicate on the "template_key" field.
func TemplateKeyNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldTemplateKey, v))
}

// TemplateKeyIn applies the In predicate on the "template_key" field.
func TemplateKeyIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldTemplateKey, vs...))
}

// TemplateKeyNotIn applies the NotIn predicate on the "template_key" field.
func TemplateKeyNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldTemplateKey, vs...))
}

// TemplateKeyGT applies the GT predicate on the "template_key" field.
func TemplateKeyGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldTemplateKey, v))
}

// TemplateKeyGTE applies the GTE predicate on the "template_key" field.
func TemplateKeyGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldTemplateKey, v))
}

// TemplateKeyLT applies the LT predicate on the "template_key" field.
func TemplateKeyLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldTemplateKey, v))
}

// TemplateKeyLTE applies the LTE predicate on the "template_key" field.
func TemplateKeyLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldTemplateKey, v))
}

// TemplateKeyContains applies the Contains predicate on the "template_key" field.
func TemplateKeyContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldTemplateKey, v))
}

// TemplateKeyHasPrefix applies the HasPrefix predicate on the "template_key" field.
func TemplateKeyHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldTemplateKey, v))
}

// TemplateKeyHasSuffix applies the HasSuffix predicate on the "template_key" field.
func TemplateKeyHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldTemplateKey, v))
}

// TemplateKeyEqualFold applies the EqualFold predicate on the "template_key" field.
func TemplateKeyEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldTemplateKey, v))
}

// TemplateKeyContainsFold applies the ContainsFold predicate on the "template_key" field.
func TemplateKeyContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldTemplateKey, v))
}

// ContextTypeEQ applies the EQ predicate on the "context_type" field.
func ContextTypeEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldContextType, v))
}

// ContextTypeNEQ applies the NEQ predicate on the "context_type" field.
func ContextTypeNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldContextType, v))
}

// ContextTypeIn applies the In predicate on the "context_type" field.
func ContextTypeIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldContextType, vs...))
}

// ContextTypeNotIn applies the NotIn predicate on the "context_type" field.
func ContextTypeNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldContextType, vs...))
}

// ContextTypeGT applies the GT predicate on the "context_type" field.
func ContextTypeGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldContextType, v))
}

// ContextTypeGTE applies the GTE predicate on the "context_type" field.
func ContextTypeGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldContextType, v))
}

// ContextTypeLT applies the LT predicate on the "context_type" field.
func ContextTypeLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldContextType, v))
}

// ContextTypeLTE applies the LTE predicate on the "context_type" field.
func ContextTypeLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldContextType, v))
}

// ContextTypeContains applies the Contains predicate on the "context_type" field.
func ContextTypeContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldContextType, v))
}

// ContextTypeHasPrefix applies the HasPrefix predicate on the "context_type" field.
func ContextTypeHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldContextType, v))
}

// ContextTypeHasSuffix applies the HasSuffix predicate on the "context_type" field.
func ContextTypeHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldContextType, v))
}

// ContextTypeEqualFold applies the EqualFold predicate on the "context_type" field.
func ContextTypeEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldContextType, v))
}

// ContextTypeContainsFold applies the ContainsFold predicate on the "context_type" field.
func ContextTypeContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldContextType, v))
}

// ContextIDEQ applies the EQ predicate on the "context_id" field.
func ContextIDEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldContextID, v))
}

// ContextIDNEQ applies the NEQ predicate on the "context_id" field.
func ContextIDNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldContextID, v))
}

// ContextIDIn applies the In predicate on the "context_id" field.
func ContextIDIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldContextID, vs...))
}

// ContextIDNotIn applies the NotIn predicate on the "context_id" field.
func ContextIDNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldContextID, vs...))
}

// ContextIDGT applies the GT predicate on the "context_id" field.
func ContextIDGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldContextID, v))
}

// ContextIDGTE applies the GTE predicate on the "context_id" field.
func ContextIDGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldContextID, v))
}

// ContextIDLT applies the LT predicate on the "context_id" field.
func ContextIDLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldContextID, v))
}

// ContextIDLTE applies the LTE predicate on the "context_id" field.
func ContextIDLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldContextID, v))
}

// ContextIDContains applies the Contains predicate on the "context_id" field.
func ContextIDContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldContextID, v))
}

// ContextIDHasPrefix applies the HasPrefix predicate on the "context_id" field.
func ContextIDHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldContextID, v))
}

// ContextIDHasSuffix applies the HasSuffix predicate on the "context_id" field.
func ContextIDHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldContextID, v))
}

// ContextIDEqualFold applies the EqualFold predicate on the "context_id" field.
func ContextIDEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldContextID, v))
}

// ContextIDContainsFold applies the ContainsFold predicate on the "context_id" field.
func ContextIDContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldContextID, v))
}

// AssigneeIDEQ applies the EQ predicate on the "assignee_id" field.
func AssigneeIDEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldAssigneeID, v))
}

// AssigneeIDNEQ applies the NEQ predicate on the "assignee_id" field.
func AssigneeIDNEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldAssigneeID, v))
}

// AssigneeIDIn applies the In predicate on the "assignee_id" field.
func AssigneeIDIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldAssigneeID, vs...))
}

// AssigneeIDNotIn applies the NotIn predicate on the "assignee_id" field.
func AssigneeIDNotIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldAssigneeID, vs...))
}

// AssigneeIDGT applies the GT predicate on the "assignee_id" field.
func AssigneeIDGT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldAssigneeID, v))
}

// AssigneeIDGTE applies the GTE predicate on the "assignee_id" field.
func AssigneeIDGTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldAssigneeID, v))
}

// AssigneeIDLT applies the LT predicate on the "assignee_id" field.
func AssigneeIDLT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldAssigneeID, v))
}

// AssigneeIDLTE applies the LTE predicate on the "assignee_id" field.
func AssigneeIDLTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldAssigneeID, v))
}

// AssigneeIDIsNil applies the IsNil predicate on the "assignee_id" field.
func AssigneeIDIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldAssigneeID))
}

// AssigneeIDNotNil applies the NotNil predicate on the "assignee_id" field.
func AssigneeIDNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldAssigneeID))
}

// EscalatedAtEQ applies the EQ predicate on the "escalated_at" field.
func EscalatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalatedAt, v))
}

// EscalatedAtNEQ applies the NEQ predicate on the "escalated_at" field.
func EscalatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldEscalatedAt, v))
}

// EscalatedAtIn applies the In predicate on the "escalated_at" field.
func EscalatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldEscalatedAt, vs...))
}

// EscalatedAtNotIn applies the NotIn predicate on the "escalated_at" field.
func EscalatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldEscalatedAt, vs...))
}

// EscalatedAtGT applies the GT predicate on the "escalated_at" field.
func EscalatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldEscalatedAt, v))
}

// EscalatedAtGTE applies the GTE predicate on the "escalated_at" field.
func EscalatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldEscalatedAt, v))
}

// EscalatedAtLT applies the LT predicate on the "escalated_at" field.
func EscalatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldEscalatedAt, v))
}

// EscalatedAtLTE applies the LTE predicate on the "escalated_at" field.
func EscalatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldEscalatedAt, v))
}

// EscalatedAtIsNil applies the IsNil predicate on the "escalated_at" field.
func EscalatedAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldEscalatedAt))
}

// EscalatedAtNotNil applies the NotNil predicate on the "escalated_at" field.
func EscalatedAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldEscalatedAt))
}

// EscalatedByEQ applies the EQ predicate on the "escalated_by" field.
func EscalatedByEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalatedBy, v))
}

// EscalatedByNEQ applies the NEQ predicate on the "escalated_by" field.
func EscalatedByNEQ(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldEscalatedBy, v))
}

// EscalatedByIn applies the In predicate on the "escalated_by" field.
func EscalatedByIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldEscalatedBy, vs...))
}

// EscalatedByNotIn applies the NotIn predicate on the "escalated_by" field.
func EscalatedByNotIn(vs ...int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldEscalatedBy, vs...))
}

// EscalatedByGT applies the GT predicate on the "escalated_by" field.
func EscalatedByGT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldEscalatedBy, v))
}

// EscalatedByGTE applies the GTE predicate on the "escalated_by" field.
func EscalatedByGTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldEscalatedBy, v))
}

// EscalatedByLT applies the LT predicate on the "escalated_by" field.
func EscalatedByLT(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldEscalatedBy, v))
}

// EscalatedByLTE applies the LTE predicate on the "escalated_by" field.
func EscalatedByLTE(v int64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldEscalatedBy, v))
}

// EscalatedByIsNil applies the IsNil predicate on the "escalated_by" field.
func EscalatedByIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldEscalatedBy))
}

// EscalatedByNotNil applies the NotNil predicate on the "escalated_by" field.
func EscalatedByNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldEscalatedBy))
}

// EscalationReasonEQ applies the EQ predicate on the "escalation_reason" field.
func EscalationReasonEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEscalationReason, v))
}

// EscalationReasonNEQ applies the NEQ predicate on the "escalation_reason" field.
func EscalationReasonNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldEscalationReason, v))
}

// EscalationReasonIn applies the In predicate on the "escalation_reason" field.
func EscalationReasonIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldEscalationReason, vs...))
}

// EscalationReasonNotIn applies the NotIn predicate on the "escalation_reason" field.
func EscalationReasonNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldEscalationReason, vs...))
}

// EscalationReasonGT applies the GT predicate on the "escalation_reason" field.
func EscalationReasonGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldEscalationReason, v))
}

// EscalationReasonGTE applies the GTE predicate on the "escalation_reason" field.
func EscalationReasonGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldEscalationReason, v))
}

// EscalationReasonLT applies the LT predicate on the "escalation_reason" field.
func EscalationReasonLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldEscalationReason, v))
}

// EscalationReasonLTE applies the LTE predicate on the "escalation_reason" field.
func EscalationReasonLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldEscalationReason, v))
}

// EscalationReasonContains applies the Contains predicate on the "escalation_reason" field.
func EscalationReasonContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldEscalationReason, v))
}

// EscalationReasonHasPrefix applies the HasPrefix predicate on the "escalation_reason" field.
func EscalationReasonHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldEscalationReason, v))
}

// EscalationReasonHasSuffix applies the HasSuffix predicate on the "escalation_reason" field.
func EscalationReasonHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldEscalationReason, v))
}

// EscalationReasonEqualFold applies the EqualFold predicate on the "escalation_reason" field.
func EscalationReasonEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldEscalationReason, v))
}

// EscalationReasonContainsFold applies the ContainsFold predicate on the "escalation_reason" field.
func EscalationReasonContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldEscalationReason, v))
}

// SLADueAtEQ applies the EQ predicate on the "sla_due_at" field.
func SLADueAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSLADueAt, v))
}

// SLADueAtNEQ applies the NEQ predicate on the "sla_due_at" field.
func SLADueAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSLADueAt, v))
}

// SLADueAtIn applies the In predicate on the "sla_due_at" field.
func SLADueAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSLADueAt, vs...))
}

// SLADueAtNotIn applies the NotIn predicate on the "sla_due_at" field.
func SLADueAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSLADueAt, vs...))
}

// SLADueAtGT applies the GT predicate on the "sla_due_at" field.
func SLADueAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSLADueAt, v))
}

// SLADueAtGTE applies the GTE predicate on the "sla_due_at" field.
func SLADueAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSLADueAt, v))
}

// SLADueAtLT applies the LT predicate on the "sla_due_at" field.
func SLADueAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSLADueAt, v))
}

// SLADueAtLTE applies the LTE predicate on the "sla_due_at" field.
func SLADueAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSLADueAt, v))
}

// SLADueAtIsNil applies the IsNil predicate on the "sla_due_at" field.
func SLADueAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldSLADueAt))
}

// SLADueAtNotNil applies the NotNil predicate on the "sla_due_at" field.
func SLADueAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldSLADueAt))
}

// SLARemindedAtEQ applies the EQ predicate on the "sla_reminded_at" field.
func SLARemindedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSLARemindedAt, v))
}

// SLARemindedAtNEQ applies the NEQ predicate on the "sla_reminded_at" field.
func SLARemindedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSLARemindedAt, v))
}

// SLARemindedAtIn applies the In predicate on the "sla_reminded_at" field.
func SLARemindedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSLARemindedAt, vs...))
}

// SLARemindedAtNotIn applies the NotIn predicate on the "sla_reminded_at" field.
func SLARemindedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSLARemindedAt, vs...))
}

// SLARemindedAtGT applies the GT predicate on the "sla_reminded_at" field.
func SLARemindedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSLARemindedAt, v))
}

// SLARemindedAtGTE applies the GTE predicate on the "sla_reminded_at" field.
func SLARemindedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSLARemindedAt, v))
}

// SLARemindedAtLT applies the LT predicate on the "sla_reminded_at" field.
func SLARemindedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSLARemindedAt, v))
}

// SLARemindedAtLTE applies the LTE predicate on the "sla_reminded_at" field.
func SLARemindedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSLARemindedAt, v))
}

// SLARemindedAtIsNil applies the IsNil predicate on the "sla_reminded_at" field.
func SLARemindedAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldSLARemindedAt))
}

// SLARemindedAtNotNil applies the NotNil predicate on the "sla_reminded_at" field.
func SLARemindedAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldSLARemindedAt))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldLastMessageAt, v))
}

// LastUserMessageAtEQ applies the EQ predicate on the "last_user_message_at" field.
func LastUserMessageAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastUserMessageAt, v))
}

// LastUserMessageAtNEQ applies the NEQ predicate on the "last_user_message_at" field.
func LastUserMessageAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldLastUserMessageAt, v))
}

// LastUserMessageAtIn applies the In predicate on the "last_user_message_at" field.
func LastUserMessageAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldLastUserMessageAt, vs...))
}

// LastUserMessageAtNotIn applies the NotIn predicate on the "last_user_message_at" field.
func LastUserMessageAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldLastUserMessageAt, vs...))
}

// LastUserMessageAtGT applies the GT predicate on the "last_user_message_at" field.
func LastUserMessageAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldLastUserMessageAt, v))
}

// LastUserMessageAtGTE applies the GTE predicate on the "last_user_message_at" field.
func LastUserMessageAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldLastUserMessageAt, v))
}

// LastUserMessageAtLT applies the LT predicate on the "last_user_message_at" field.
func LastUserMessageAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldLastUserMessageAt, v))
}

// LastUserMessageAtLTE applies the LTE predicate on the "last_user_message_at" field.
func LastUserMessageAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldLastUserMessageAt, v))
}

// LastUserMessageAtIsNil applies the IsNil predicate on the "last_user_message_at" field.
func LastUserMessageAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldLastUserMessageAt))
}

// LastUserMessageAtNotNil applies the NotNil predicate on the "last_user_message_at" field.
func LastUserMessageAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldLastUserMessageAt))
}

// LastAdminMessageAtEQ applies the EQ predicate on the "last_admin_message_at" field.
func LastAdminMessageAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtNEQ applies the NEQ predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtIn applies the In predicate on the "last_admin_message_at" field.
func LastAdminMessageAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldLastAdminMessageAt, vs...))
}

// LastAdminMessageAtNotIn applies the NotIn predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldLastAdminMessageAt, vs...))
}

// LastAdminMessageAtGT applies the GT predicate on the "last_admin_message_at" field.
func LastAdminMessageAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtGTE applies the GTE predicate on the "last_admin_message_at" field.
func LastAdminMessageAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtLT applies the LT predicate on the "last_admin_message_at" field.
func LastAdminMessageAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtLTE applies the LTE predicate on the "last_admin_message_at" field.
func LastAdminMessageAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtIsNil applies the IsNil predicate on the "last_admin_message_at" field.
func LastAdminMessageAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldLastAdminMessageAt))
}

// LastAdminMessageAtNotNil applies the NotNil predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldLastAdminMessageAt))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldResolvedAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldClosedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.TicketMessage) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReads applies the HasEdge predicate on the "reads" edge.
func HasReads() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReadsTable, ReadsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReadsWith applies the HasEdge predicate on the "reads" edge with a given conditions (other predicates).
func HasReadsWith(preds ...predicate.TicketRead) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newReadsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.NotPredicates(p))
}
