// Code generated by ent, DO NOT EDIT.

package upstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldProxyID, v))
}

// LastProbeAt applies equality check predicate on the "last_probe_at" field. It's identical to LastProbeAtEQ.
func LastProbeAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeError applies equality check predicate on the "last_probe_error" field. It's identical to LastProbeErrorEQ.
func LastProbeError(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastProbeError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldBaseURL, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldKind, vs...))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldProxyID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldStatus, vs...))
}

// LastProbeAtEQ applies the EQ predicate on the "last_probe_at" field.
func LastProbeAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAtNEQ applies the NEQ predicate on the "last_probe_at" field.
func LastProbeAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLastProbeAt, v))
}

// LastProbeAtIn applies the In predicate on the "last_probe_at" field.
func LastProbeAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLastProbeAt, vs...))
}

// LastProbeAtNotIn applies the NotIn predicate on the "last_probe_at" field.
func LastProbeAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLastProbeAt, vs...))
}

// LastProbeAtGT applies the GT predicate on the "last_probe_at" field.
func LastProbeAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLastProbeAt, v))
}

// LastProbeAtGTE applies the GTE predicate on the "last_probe_at" field.
func LastProbeAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLastProbeAt, v))
}

// LastProbeAtLT applies the LT predicate on the "last_probe_at" field.
func LastProbeAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLastProbeAt, v))
}

// LastProbeAtLTE applies the LTE predicate on the "last_probe_at" field.
func LastProbeAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLastProbeAt, v))
}

// LastProbeAtIsNil applies the IsNil predicate on the "last_probe_at" field.
func LastProbeAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLastProbeAt))
}

// LastProbeAtNotNil applies the NotNil predicate on the "last_probe_at" field.
func LastProbeAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLastProbeAt))
}

// LastProbeErrorEQ applies the EQ predicate on the "last_probe_error" field.
func LastProbeErrorEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastProbeError, v))
}

// LastProbeErrorNEQ applies the NEQ predicate on the "last_probe_error" field.
func LastProbeErrorNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLastProbeError, v))
}

// LastProbeErrorIn applies the In predicate on the "last_probe_error" field.
func LastProbeErrorIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLastProbeError, vs...))
}

// LastProbeErrorNotIn applies the NotIn predicate on the "last_probe_error" field.
func LastProbeErrorNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLastProbeError, vs...))
}

// LastProbeErrorGT applies the GT predicate on the "last_probe_error" field.
func LastProbeErrorGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLastProbeError, v))
}

// LastProbeErrorGTE applies the GTE predicate on the "last_probe_error" field.
func LastProbeErrorGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLastProbeError, v))
}

// LastProbeErrorLT applies the LT predicate on the "last_probe_error" field.
func LastProbeErrorLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLastProbeError, v))
}

// LastProbeErrorLTE applies the LTE predicate on the "last_probe_error" field.
func LastProbeErrorLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLastProbeError, v))
}

// LastProbeErrorContains applies the Contains predicate on the "last_probe_error" field.
func LastProbeErrorContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldLastProbeError, v))
}

// LastProbeErrorHasPrefix applies the HasPrefix predicate on the "last_probe_error" field.
func LastProbeErrorHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldLastProbeError, v))
}

// LastProbeErrorHasSuffix applies the HasSuffix predicate on the "last_probe_error" field.
func LastProbeErrorHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldLastProbeError, v))
}

// LastProbeErrorIsNil applies the IsNil predicate on the "last_probe_error" field.
func LastProbeErrorIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLastProbeError))
}

// LastProbeErrorNotNil applies the NotNil predicate on the "last_probe_error" field.
func LastProbeErrorNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLastProbeError))
}

// LastProbeErrorEqualFold applies the EqualFold predicate on the "last_probe_error" field.
func LastProbeErrorEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldLastProbeError, v))
}

// LastProbeErrorContainsFold applies the ContainsFold predicate on the "last_probe_error" field.
func LastProbeErrorContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldLastProbeError, v))
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.Upstream {
	return predicate.Upstream(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.Upstream {
	return predicate.Upstream(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Upstream {
	return predicate.Upstream(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Upstream {
	return predicate.Upstream(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.NotPredicates(p))
}
