// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitor"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountMonitorDelete is the builder for deleting a AccountMonitor entity.
type AccountMonitorDelete struct {
	config
	hooks    []Hook
	mutation *AccountMonitorMutation
}

// Where appends a list predicates to the AccountMonitorDelete builder.
func (_d *AccountMonitorDelete) Where(ps ...predicate.AccountMonitor) *AccountMonitorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountMonitorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountMonitorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountMonitorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountmonitor.Table, sqlgraph.NewFieldSpec(accountmonitor.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountMonitorDeleteOne is the builder for deleting a single AccountMonitor entity.
type AccountMonitorDeleteOne struct {
	_d *AccountMonitorDelete
}

// Where appends a list predicates to the AccountMonitorDelete builder.
func (_d *AccountMonitorDeleteOne) Where(ps ...predicate.AccountMonitor) *AccountMonitorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountMonitorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountmonitor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountMonitorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
