// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitor"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitorcheck"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountMonitorUpdate is the builder for updating AccountMonitor entities.
type AccountMonitorUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMonitorMutation
}

// Where appends a list predicates to the AccountMonitorUpdate builder.
func (_u *AccountMonitorUpdate) Where(ps ...predicate.AccountMonitor) *AccountMonitorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountMonitorUpdate) SetUpdatedAt(v time.Time) *AccountMonitorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountMonitorUpdate) SetAccountID(v int64) *AccountMonitorUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableAccountID(v *int64) *AccountMonitorUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountMonitorUpdate) SetProvider(v accountmonitor.Provider) *AccountMonitorUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableProvider(v *accountmonitor.Provider) *AccountMonitorUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AccountMonitorUpdate) SetModel(v string) *AccountMonitorUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableModel(v *string) *AccountMonitorUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AccountMonitorUpdate) SetEnabled(v bool) *AccountMonitorUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableEnabled(v *bool) *AccountMonitorUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *AccountMonitorUpdate) SetIntervalSeconds(v int) *AccountMonitorUpdate {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableIntervalSeconds(v *int) *AccountMonitorUpdate {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *AccountMonitorUpdate) AddIntervalSeconds(v int) *AccountMonitorUpdate {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (_u *AccountMonitorUpdate) SetJitterSeconds(v int) *AccountMonitorUpdate {
	_u.mutation.ResetJitterSeconds()
	_u.mutation.SetJitterSeconds(v)
	return _u
}

// SetNillableJitterSeconds sets the "jitter_seconds" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableJitterSeconds(v *int) *AccountMonitorUpdate {
	if v != nil {
		_u.SetJitterSeconds(*v)
	}
	return _u
}

// AddJitterSeconds adds value to the "jitter_seconds" field.
func (_u *AccountMonitorUpdate) AddJitterSeconds(v int) *AccountMonitorUpdate {
	_u.mutation.AddJitterSeconds(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *AccountMonitorUpdate) SetLastCheckedAt(v time.Time) *AccountMonitorUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableLastCheckedAt(v *time.Time) *AccountMonitorUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *AccountMonitorUpdate) ClearLastCheckedAt() *AccountMonitorUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountMonitorUpdate) SetCreatedBy(v int64) *AccountMonitorUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountMonitorUpdate) SetNillableCreatedBy(v *int64) *AccountMonitorUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AccountMonitorUpdate) AddCreatedBy(v int64) *AccountMonitorUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddCheckIDs adds the "checks" edge to the AccountMonitorCheck entity by IDs.
func (_u *AccountMonitorUpdate) AddCheckIDs(ids ...int64) *AccountMonitorUpdate {
	_u.mutation.AddCheckIDs(ids...)
	return _u
}

// AddChecks adds the "checks" edges to the AccountMonitorCheck entity.
func (_u *AccountMonitorUpdate) AddChecks(v ...*AccountMonitorCheck) *AccountMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountMonitorUpdate) SetAccount(v *Account) *AccountMonitorUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountMonitorMutation object of the builder.
func (_u *AccountMonitorUpdate) Mutation() *AccountMonitorMutation {
	return _u.mutation
}

// ClearChecks clears all "checks" edges to the AccountMonitorCheck entity.
func (_u *AccountMonitorUpdate) ClearChecks() *AccountMonitorUpdate {
	_u.mutation.ClearChecks()
	return _u
}

// RemoveCheckIDs removes the "checks" edge to AccountMonitorCheck entities by IDs.
func (_u *AccountMonitorUpdate) RemoveCheckIDs(ids ...int64) *AccountMonitorUpdate {
	_u.mutation.RemoveCheckIDs(ids...)
	return _u
}

// RemoveChecks removes "checks" edges to AccountMonitorCheck entities.
func (_u *AccountMonitorUpdate) RemoveChecks(v ...*AccountMonitorCheck) *AccountMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckIDs(ids...)
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountMonitorUpdate) ClearAccount() *AccountMonitorUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountMonitorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountMonitorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountMonitorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountMonitorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountMonitorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountmonitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountMonitorUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountmonitor.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := accountmonitor.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := accountmonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JitterSeconds(); ok {
		if err := accountmonitor.JitterSecondsValidator(v); err != nil {
			return &ValidationError{Name: "jitter_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.jitter_seconds": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountMonitor.account"`)
	}
	return nil
}

func (_u *AccountMonitorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountmonitor.Table, accountmonitor.Columns, sqlgraph.NewFieldSpec(accountmonitor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmonitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountmonitor.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(accountmonitor.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(accountmonitor.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(accountmonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(accountmonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JitterSeconds(); ok {
		_spec.SetField(accountmonitor.FieldJitterSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedJitterSeconds(); ok {
		_spec.AddField(accountmonitor.FieldJitterSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountmonitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(accountmonitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountmonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(accountmonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecksIDs(); len(nodes) > 0 && !_u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountmonitor.AccountTable,
			Columns: []string{accountmonitor.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountmonitor.AccountTable,
			Columns: []string{accountmonitor.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountmonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountMonitorUpdateOne is the builder for updating a single AccountMonitor entity.
type AccountMonitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMonitorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountMonitorUpdateOne) SetUpdatedAt(v time.Time) *AccountMonitorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountMonitorUpdateOne) SetAccountID(v int64) *AccountMonitorUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableAccountID(v *int64) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountMonitorUpdateOne) SetProvider(v accountmonitor.Provider) *AccountMonitorUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableProvider(v *accountmonitor.Provider) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AccountMonitorUpdateOne) SetModel(v string) *AccountMonitorUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableModel(v *string) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AccountMonitorUpdateOne) SetEnabled(v bool) *AccountMonitorUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableEnabled(v *bool) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *AccountMonitorUpdateOne) SetIntervalSeconds(v int) *AccountMonitorUpdateOne {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableIntervalSeconds(v *int) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *AccountMonitorUpdateOne) AddIntervalSeconds(v int) *AccountMonitorUpdateOne {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (_u *AccountMonitorUpdateOne) SetJitterSeconds(v int) *AccountMonitorUpdateOne {
	_u.mutation.ResetJitterSeconds()
	_u.mutation.SetJitterSeconds(v)
	return _u
}

// SetNillableJitterSeconds sets the "jitter_seconds" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableJitterSeconds(v *int) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetJitterSeconds(*v)
	}
	return _u
}

// AddJitterSeconds adds value to the "jitter_seconds" field.
func (_u *AccountMonitorUpdateOne) AddJitterSeconds(v int) *AccountMonitorUpdateOne {
	_u.mutation.AddJitterSeconds(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *AccountMonitorUpdateOne) SetLastCheckedAt(v time.Time) *AccountMonitorUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableLastCheckedAt(v *time.Time) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *AccountMonitorUpdateOne) ClearLastCheckedAt() *AccountMonitorUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountMonitorUpdateOne) SetCreatedBy(v int64) *AccountMonitorUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountMonitorUpdateOne) SetNillableCreatedBy(v *int64) *AccountMonitorUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AccountMonitorUpdateOne) AddCreatedBy(v int64) *AccountMonitorUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddCheckIDs adds the "checks" edge to the AccountMonitorCheck entity by IDs.
func (_u *AccountMonitorUpdateOne) AddCheckIDs(ids ...int64) *AccountMonitorUpdateOne {
	_u.mutation.AddCheckIDs(ids...)
	return _u
}

// AddChecks adds the "checks" edges to the AccountMonitorCheck entity.
func (_u *AccountMonitorUpdateOne) AddChecks(v ...*AccountMonitorCheck) *AccountMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountMonitorUpdateOne) SetAccount(v *Account) *AccountMonitorUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountMonitorMutation object of the builder.
func (_u *AccountMonitorUpdateOne) Mutation() *AccountMonitorMutation {
	return _u.mutation
}

// ClearChecks clears all "checks" edges to the AccountMonitorCheck entity.
func (_u *AccountMonitorUpdateOne) ClearChecks() *AccountMonitorUpdateOne {
	_u.mutation.ClearChecks()
	return _u
}

// RemoveCheckIDs removes the "checks" edge to AccountMonitorCheck entities by IDs.
func (_u *AccountMonitorUpdateOne) RemoveCheckIDs(ids ...int64) *AccountMonitorUpdateOne {
	_u.mutation.RemoveCheckIDs(ids...)
	return _u
}

// RemoveChecks removes "checks" edges to AccountMonitorCheck entities.
func (_u *AccountMonitorUpdateOne) RemoveChecks(v ...*AccountMonitorCheck) *AccountMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckIDs(ids...)
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountMonitorUpdateOne) ClearAccount() *AccountMonitorUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the AccountMonitorUpdate builder.
func (_u *AccountMonitorUpdateOne) Where(ps ...predicate.AccountMonitor) *AccountMonitorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountMonitorUpdateOne) Select(field string, fields ...string) *AccountMonitorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountMonitor entity.
func (_u *AccountMonitorUpdateOne) Save(ctx context.Context) (*AccountMonitor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountMonitorUpdateOne) SaveX(ctx context.Context) *AccountMonitor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountMonitorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountMonitorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountMonitorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountmonitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountMonitorUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountmonitor.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := accountmonitor.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := accountmonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JitterSeconds(); ok {
		if err := accountmonitor.JitterSecondsValidator(v); err != nil {
			return &ValidationError{Name: "jitter_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.jitter_seconds": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountMonitor.account"`)
	}
	return nil
}

func (_u *AccountMonitorUpdateOne) sqlSave(ctx context.Context) (_node *AccountMonitor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountmonitor.Table, accountmonitor.Columns, sqlgraph.NewFieldSpec(accountmonitor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountMonitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountmonitor.FieldID)
		for _, f := range fields {
			if !accountmonitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountmonitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmonitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountmonitor.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(accountmonitor.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(accountmonitor.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(accountmonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(accountmonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JitterSeconds(); ok {
		_spec.SetField(accountmonitor.FieldJitterSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedJitterSeconds(); ok {
		_spec.AddField(accountmonitor.FieldJitterSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountmonitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(accountmonitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountmonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(accountmonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecksIDs(); len(nodes) > 0 && !_u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountmonitor.AccountTable,
			Columns: []string{accountmonitor.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountmonitor.AccountTable,
			Columns: []string{accountmonitor.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountMonitor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountmonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
