// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitor"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitorcheck"
)

// AccountMonitorCheckCreate is the builder for creating a AccountMonitorCheck entity.
type AccountMonitorCheckCreate struct {
	config
	mutation *AccountMonitorCheckMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountMonitorID sets the "account_monitor_id" field.
func (_c *AccountMonitorCheckCreate) SetAccountMonitorID(v int64) *AccountMonitorCheckCreate {
	_c.mutation.SetAccountMonitorID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AccountMonitorCheckCreate) SetModel(v string) *AccountMonitorCheckCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountMonitorCheckCreate) SetStatus(v accountmonitorcheck.Status) *AccountMonitorCheckCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *AccountMonitorCheckCreate) SetLatencyMs(v int) *AccountMonitorCheckCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *AccountMonitorCheckCreate) SetNillableLatencyMs(v *int) *AccountMonitorCheckCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetPingLatencyMs sets the "ping_latency_ms" field.
func (_c *AccountMonitorCheckCreate) SetPingLatencyMs(v int) *AccountMonitorCheckCreate {
	_c.mutation.SetPingLatencyMs(v)
	return _c
}

// SetNillablePingLatencyMs sets the "ping_latency_ms" field if the given value is not nil.
func (_c *AccountMonitorCheckCreate) SetNillablePingLatencyMs(v *int) *AccountMonitorCheckCreate {
	if v != nil {
		_c.SetPingLatencyMs(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *AccountMonitorCheckCreate) SetMessage(v string) *AccountMonitorCheckCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *AccountMonitorCheckCreate) SetNillableMessage(v *string) *AccountMonitorCheckCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetCheckedAt sets the "checked_at" field.
func (_c *AccountMonitorCheckCreate) SetCheckedAt(v time.Time) *AccountMonitorCheckCreate {
	_c.mutation.SetCheckedAt(v)
	return _c
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_c *AccountMonitorCheckCreate) SetNillableCheckedAt(v *time.Time) *AccountMonitorCheckCreate {
	if v != nil {
		_c.SetCheckedAt(*v)
	}
	return _c
}

// SetMonitorID sets the "monitor" edge to the AccountMonitor entity by ID.
func (_c *AccountMonitorCheckCreate) SetMonitorID(id int64) *AccountMonitorCheckCreate {
	_c.mutation.SetMonitorID(id)
	return _c
}

// SetMonitor sets the "monitor" edge to the AccountMonitor entity.
func (_c *AccountMonitorCheckCreate) SetMonitor(v *AccountMonitor) *AccountMonitorCheckCreate {
	return _c.SetMonitorID(v.ID)
}

// Mutation returns the AccountMonitorCheckMutation object of the builder.
func (_c *AccountMonitorCheckCreate) Mutation() *AccountMonitorCheckMutation {
	return _c.mutation
}

// Save creates the AccountMonitorCheck in the database.
func (_c *AccountMonitorCheckCreate) Save(ctx context.Context) (*AccountMonitorCheck, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountMonitorCheckCreate) SaveX(ctx context.Context) *AccountMonitorCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountMonitorCheckCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountMonitorCheckCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountMonitorCheckCreate) defaults() {
	if _, ok := _c.mutation.Message(); !ok {
		v := accountmonitorcheck.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		v := accountmonitorcheck.DefaultCheckedAt()
		_c.mutation.SetCheckedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountMonitorCheckCreate) check() error {
	if _, ok := _c.mutation.AccountMonitorID(); !ok {
		return &ValidationError{Name: "account_monitor_id", err: errors.New(`ent: missing required field "AccountMonitorCheck.account_monitor_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AccountMonitorCheck.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := accountmonitorcheck.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AccountMonitorCheck.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountMonitorCheck.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountmonitorcheck.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountMonitorCheck.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := accountmonitorcheck.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "AccountMonitorCheck.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		return &ValidationError{Name: "checked_at", err: errors.New(`ent: missing required field "AccountMonitorCheck.checked_at"`)}
	}
	if len(_c.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "AccountMonitorCheck.monitor"`)}
	}
	return nil
}

func (_c *AccountMonitorCheckCreate) sqlSave(ctx context.Context) (*AccountMonitorCheck, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountMonitorCheckCreate) createSpec() (*AccountMonitorCheck, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountMonitorCheck{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountmonitorcheck.Table, sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(accountmonitorcheck.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountmonitorcheck.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(accountmonitorcheck.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.PingLatencyMs(); ok {
		_spec.SetField(accountmonitorcheck.FieldPingLatencyMs, field.TypeInt, value)
		_node.PingLatencyMs = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(accountmonitorcheck.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.CheckedAt(); ok {
		_spec.SetField(accountmonitorcheck.FieldCheckedAt, field.TypeTime, value)
		_node.CheckedAt = value
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountmonitorcheck.MonitorTable,
			Columns: []string{accountmonitorcheck.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountMonitorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountMonitorCheck.Create().
//		SetAccountMonitorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountMonitorCheckUpsert) {
//			SetAccountMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountMonitorCheckCreate) OnConflict(opts ...sql.ConflictOption) *AccountMonitorCheckUpsertOne {
	_c.conflict = opts
	return &AccountMonitorCheckUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountMonitorCheckCreate) OnConflictColumns(columns ...string) *AccountMonitorCheckUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountMonitorCheckUpsertOne{
		create: _c,
	}
}

type (
	// AccountMonitorCheckUpsertOne is the builder for "upsert"-ing
	//  one AccountMonitorCheck node.
	AccountMonitorCheckUpsertOne struct {
		create *AccountMonitorCheckCreate
	}

	// AccountMonitorCheckUpsert is the "OnConflict" setter.
	AccountMonitorCheckUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountMonitorID sets the "account_monitor_id" field.
func (u *AccountMonitorCheckUpsert) SetAccountMonitorID(v int64) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldAccountMonitorID, v)
	return u
}

// UpdateAccountMonitorID sets the "account_monitor_id" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateAccountMonitorID() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldAccountMonitorID)
	return u
}

// SetModel sets the "model" field.
func (u *AccountMonitorCheckUpsert) SetModel(v string) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateModel() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldModel)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountMonitorCheckUpsert) SetStatus(v accountmonitorcheck.Status) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateStatus() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldStatus)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AccountMonitorCheckUpsert) SetLatencyMs(v int) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateLatencyMs() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AccountMonitorCheckUpsert) AddLatencyMs(v int) *AccountMonitorCheckUpsert {
	u.Add(accountmonitorcheck.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *AccountMonitorCheckUpsert) ClearLatencyMs() *AccountMonitorCheckUpsert {
	u.SetNull(accountmonitorcheck.FieldLatencyMs)
	return u
}

// SetPingLatencyMs sets the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsert) SetPingLatencyMs(v int) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldPingLatencyMs, v)
	return u
}

// UpdatePingLatencyMs sets the "ping_latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdatePingLatencyMs() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldPingLatencyMs)
	return u
}

// AddPingLatencyMs adds v to the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsert) AddPingLatencyMs(v int) *AccountMonitorCheckUpsert {
	u.Add(accountmonitorcheck.FieldPingLatencyMs, v)
	return u
}

// ClearPingLatencyMs clears the value of the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsert) ClearPingLatencyMs() *AccountMonitorCheckUpsert {
	u.SetNull(accountmonitorcheck.FieldPingLatencyMs)
	return u
}

// SetMessage sets the "message" field.
func (u *AccountMonitorCheckUpsert) SetMessage(v string) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateMessage() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *AccountMonitorCheckUpsert) ClearMessage() *AccountMonitorCheckUpsert {
	u.SetNull(accountmonitorcheck.FieldMessage)
	return u
}

// SetCheckedAt sets the "checked_at" field.
func (u *AccountMonitorCheckUpsert) SetCheckedAt(v time.Time) *AccountMonitorCheckUpsert {
	u.Set(accountmonitorcheck.FieldCheckedAt, v)
	return u
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsert) UpdateCheckedAt() *AccountMonitorCheckUpsert {
	u.SetExcluded(accountmonitorcheck.FieldCheckedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountMonitorCheckUpsertOne) UpdateNewValues() *AccountMonitorCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountMonitorCheckUpsertOne) Ignore() *AccountMonitorCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountMonitorCheckUpsertOne) DoNothing() *AccountMonitorCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountMonitorCheckCreate.OnConflict
// documentation for more info.
func (u *AccountMonitorCheckUpsertOne) Update(set func(*AccountMonitorCheckUpsert)) *AccountMonitorCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountMonitorCheckUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountMonitorID sets the "account_monitor_id" field.
func (u *AccountMonitorCheckUpsertOne) SetAccountMonitorID(v int64) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetAccountMonitorID(v)
	})
}

// UpdateAccountMonitorID sets the "account_monitor_id" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateAccountMonitorID() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateAccountMonitorID()
	})
}

// SetModel sets the "model" field.
func (u *AccountMonitorCheckUpsertOne) SetModel(v string) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateModel() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *AccountMonitorCheckUpsertOne) SetStatus(v accountmonitorcheck.Status) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateStatus() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) SetLatencyMs(v int) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) AddLatencyMs(v int) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateLatencyMs() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) ClearLatencyMs() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearLatencyMs()
	})
}

// SetPingLatencyMs sets the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) SetPingLatencyMs(v int) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetPingLatencyMs(v)
	})
}

// AddPingLatencyMs adds v to the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) AddPingLatencyMs(v int) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.AddPingLatencyMs(v)
	})
}

// UpdatePingLatencyMs sets the "ping_latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdatePingLatencyMs() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdatePingLatencyMs()
	})
}

// ClearPingLatencyMs clears the value of the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertOne) ClearPingLatencyMs() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearPingLatencyMs()
	})
}

// SetMessage sets the "message" field.
func (u *AccountMonitorCheckUpsertOne) SetMessage(v string) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateMessage() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *AccountMonitorCheckUpsertOne) ClearMessage() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearMessage()
	})
}

// SetCheckedAt sets the "checked_at" field.
func (u *AccountMonitorCheckUpsertOne) SetCheckedAt(v time.Time) *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertOne) UpdateCheckedAt() *AccountMonitorCheckUpsertOne {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateCheckedAt()
	})
}

// Exec executes the query.
func (u *AccountMonitorCheckUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountMonitorCheckCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountMonitorCheckUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountMonitorCheckUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountMonitorCheckUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountMonitorCheckCreateBulk is the builder for creating many AccountMonitorCheck entities in bulk.
type AccountMonitorCheckCreateBulk struct {
	config
	err      error
	builders []*AccountMonitorCheckCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountMonitorCheck entities in the database.
func (_c *AccountMonitorCheckCreateBulk) Save(ctx context.Context) ([]*AccountMonitorCheck, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountMonitorCheck, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMonitorCheckMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountMonitorCheckCreateBulk) SaveX(ctx context.Context) []*AccountMonitorCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountMonitorCheckCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountMonitorCheckCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountMonitorCheck.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountMonitorCheckUpsert) {
//			SetAccountMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountMonitorCheckCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountMonitorCheckUpsertBulk {
	_c.conflict = opts
	return &AccountMonitorCheckUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountMonitorCheckCreateBulk) OnConflictColumns(columns ...string) *AccountMonitorCheckUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountMonitorCheckUpsertBulk{
		create: _c,
	}
}

// AccountMonitorCheckUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountMonitorCheck nodes.
type AccountMonitorCheckUpsertBulk struct {
	create *AccountMonitorCheckCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountMonitorCheckUpsertBulk) UpdateNewValues() *AccountMonitorCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountMonitorCheck.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountMonitorCheckUpsertBulk) Ignore() *AccountMonitorCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountMonitorCheckUpsertBulk) DoNothing() *AccountMonitorCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountMonitorCheckCreateBulk.OnConflict
// documentation for more info.
func (u *AccountMonitorCheckUpsertBulk) Update(set func(*AccountMonitorCheckUpsert)) *AccountMonitorCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountMonitorCheckUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountMonitorID sets the "account_monitor_id" field.
func (u *AccountMonitorCheckUpsertBulk) SetAccountMonitorID(v int64) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetAccountMonitorID(v)
	})
}

// UpdateAccountMonitorID sets the "account_monitor_id" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateAccountMonitorID() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateAccountMonitorID()
	})
}

// SetModel sets the "model" field.
func (u *AccountMonitorCheckUpsertBulk) SetModel(v string) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateModel() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *AccountMonitorCheckUpsertBulk) SetStatus(v accountmonitorcheck.Status) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateStatus() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) SetLatencyMs(v int) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) AddLatencyMs(v int) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateLatencyMs() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) ClearLatencyMs() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearLatencyMs()
	})
}

// SetPingLatencyMs sets the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) SetPingLatencyMs(v int) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetPingLatencyMs(v)
	})
}

// AddPingLatencyMs adds v to the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) AddPingLatencyMs(v int) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.AddPingLatencyMs(v)
	})
}

// UpdatePingLatencyMs sets the "ping_latency_ms" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdatePingLatencyMs() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdatePingLatencyMs()
	})
}

// ClearPingLatencyMs clears the value of the "ping_latency_ms" field.
func (u *AccountMonitorCheckUpsertBulk) ClearPingLatencyMs() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearPingLatencyMs()
	})
}

// SetMessage sets the "message" field.
func (u *AccountMonitorCheckUpsertBulk) SetMessage(v string) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateMessage() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *AccountMonitorCheckUpsertBulk) ClearMessage() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.ClearMessage()
	})
}

// SetCheckedAt sets the "checked_at" field.
func (u *AccountMonitorCheckUpsertBulk) SetCheckedAt(v time.Time) *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *AccountMonitorCheckUpsertBulk) UpdateCheckedAt() *AccountMonitorCheckUpsertBulk {
	return u.Update(func(s *AccountMonitorCheckUpsert) {
		s.UpdateCheckedAt()
	})
}

// Exec executes the query.
func (u *AccountMonitorCheckUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountMonitorCheckCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountMonitorCheckCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountMonitorCheckUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
