// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitor"
	"github.com/Wei-Shaw/sub2api/ent/accountmonitorcheck"
)

// AccountMonitorCreate is the builder for creating a AccountMonitor entity.
type AccountMonitorCreate struct {
	config
	mutation *AccountMonitorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountMonitorCreate) SetCreatedAt(v time.Time) *AccountMonitorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableCreatedAt(v *time.Time) *AccountMonitorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountMonitorCreate) SetUpdatedAt(v time.Time) *AccountMonitorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableUpdatedAt(v *time.Time) *AccountMonitorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountMonitorCreate) SetAccountID(v int64) *AccountMonitorCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AccountMonitorCreate) SetProvider(v accountmonitor.Provider) *AccountMonitorCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableProvider(v *accountmonitor.Provider) *AccountMonitorCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AccountMonitorCreate) SetModel(v string) *AccountMonitorCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableModel(v *string) *AccountMonitorCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AccountMonitorCreate) SetEnabled(v bool) *AccountMonitorCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableEnabled(v *bool) *AccountMonitorCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *AccountMonitorCreate) SetIntervalSeconds(v int) *AccountMonitorCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableIntervalSeconds(v *int) *AccountMonitorCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (_c *AccountMonitorCreate) SetJitterSeconds(v int) *AccountMonitorCreate {
	_c.mutation.SetJitterSeconds(v)
	return _c
}

// SetNillableJitterSeconds sets the "jitter_seconds" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableJitterSeconds(v *int) *AccountMonitorCreate {
	if v != nil {
		_c.SetJitterSeconds(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *AccountMonitorCreate) SetLastCheckedAt(v time.Time) *AccountMonitorCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *AccountMonitorCreate) SetNillableLastCheckedAt(v *time.Time) *AccountMonitorCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AccountMonitorCreate) SetCreatedBy(v int64) *AccountMonitorCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// AddCheckIDs adds the "checks" edge to the AccountMonitorCheck entity by IDs.
func (_c *AccountMonitorCreate) AddCheckIDs(ids ...int64) *AccountMonitorCreate {
	_c.mutation.AddCheckIDs(ids...)
	return _c
}

// AddChecks adds the "checks" edges to the AccountMonitorCheck entity.
func (_c *AccountMonitorCreate) AddChecks(v ...*AccountMonitorCheck) *AccountMonitorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountMonitorCreate) SetAccount(v *Account) *AccountMonitorCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountMonitorMutation object of the builder.
func (_c *AccountMonitorCreate) Mutation() *AccountMonitorMutation {
	return _c.mutation
}

// Save creates the AccountMonitor in the database.
func (_c *AccountMonitorCreate) Save(ctx context.Context) (*AccountMonitor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountMonitorCreate) SaveX(ctx context.Context) *AccountMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountMonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountMonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountMonitorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountmonitor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountmonitor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := accountmonitor.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := accountmonitor.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := accountmonitor.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := accountmonitor.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.JitterSeconds(); !ok {
		v := accountmonitor.DefaultJitterSeconds
		_c.mutation.SetJitterSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountMonitorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountMonitor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountMonitor.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountMonitor.account_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AccountMonitor.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := accountmonitor.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AccountMonitor.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := accountmonitor.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AccountMonitor.enabled"`)}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "AccountMonitor.interval_seconds"`)}
	}
	if v, ok := _c.mutation.IntervalSeconds(); ok {
		if err := accountmonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.interval_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JitterSeconds(); !ok {
		return &ValidationError{Name: "jitter_seconds", err: errors.New(`ent: missing required field "AccountMonitor.jitter_seconds"`)}
	}
	if v, ok := _c.mutation.JitterSeconds(); ok {
		if err := accountmonitor.JitterSecondsValidator(v); err != nil {
			return &ValidationError{Name: "jitter_seconds", err: fmt.Errorf(`ent: validator failed for field "AccountMonitor.jitter_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "AccountMonitor.created_by"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountMonitor.account"`)}
	}
	return nil
}

func (_c *AccountMonitorCreate) sqlSave(ctx context.Context) (*AccountMonitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountMonitorCreate) createSpec() (*AccountMonitor, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountMonitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountmonitor.Table, sqlgraph.NewFieldSpec(accountmonitor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountmonitor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmonitor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(accountmonitor.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(accountmonitor.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(accountmonitor.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(accountmonitor.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := _c.mutation.JitterSeconds(); ok {
		_spec.SetField(accountmonitor.FieldJitterSeconds, field.TypeInt, value)
		_node.JitterSeconds = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountmonitor.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(accountmonitor.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountmonitor.ChecksTable,
			Columns: []string{accountmonitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountmonitorcheck.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountmonitor.AccountTable,
			Columns: []string{accountmonitor.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountMonitor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountMonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountMonitorCreate) OnConflict(opts ...sql.ConflictOption) *AccountMonitorUpsertOne {
	_c.conflict = opts
	return &AccountMonitorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountMonitorCreate) OnConflictColumns(columns ...string) *AccountMonitorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountMonitorUpsertOne{
		create: _c,
	}
}

type (
	// AccountMonitorUpsertOne is the builder for "upsert"-ing
	//  one AccountMonitor node.
	AccountMonitorUpsertOne struct {
		create *AccountMonitorCreate
	}

	// AccountMonitorUpsert is the "OnConflict" setter.
	AccountMonitorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountMonitorUpsert) SetUpdatedAt(v time.Time) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateUpdatedAt() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountMonitorUpsert) SetAccountID(v int64) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateAccountID() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldAccountID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AccountMonitorUpsert) SetProvider(v accountmonitor.Provider) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateProvider() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *AccountMonitorUpsert) SetModel(v string) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateModel() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldModel)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AccountMonitorUpsert) SetEnabled(v bool) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateEnabled() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldEnabled)
	return u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *AccountMonitorUpsert) SetIntervalSeconds(v int) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldIntervalSeconds, v)
	return u
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateIntervalSeconds() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldIntervalSeconds)
	return u
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *AccountMonitorUpsert) AddIntervalSeconds(v int) *AccountMonitorUpsert {
	u.Add(accountmonitor.FieldIntervalSeconds, v)
	return u
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (u *AccountMonitorUpsert) SetJitterSeconds(v int) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldJitterSeconds, v)
	return u
}

// UpdateJitterSeconds sets the "jitter_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateJitterSeconds() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldJitterSeconds)
	return u
}

// AddJitterSeconds adds v to the "jitter_seconds" field.
func (u *AccountMonitorUpsert) AddJitterSeconds(v int) *AccountMonitorUpsert {
	u.Add(accountmonitor.FieldJitterSeconds, v)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountMonitorUpsert) SetLastCheckedAt(v time.Time) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateLastCheckedAt() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountMonitorUpsert) ClearLastCheckedAt() *AccountMonitorUpsert {
	u.SetNull(accountmonitor.FieldLastCheckedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountMonitorUpsert) SetCreatedBy(v int64) *AccountMonitorUpsert {
	u.Set(accountmonitor.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountMonitorUpsert) UpdateCreatedBy() *AccountMonitorUpsert {
	u.SetExcluded(accountmonitor.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountMonitorUpsert) AddCreatedBy(v int64) *AccountMonitorUpsert {
	u.Add(accountmonitor.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountMonitorUpsertOne) UpdateNewValues() *AccountMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountmonitor.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountMonitorUpsertOne) Ignore() *AccountMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountMonitorUpsertOne) DoNothing() *AccountMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountMonitorCreate.OnConflict
// documentation for more info.
func (u *AccountMonitorUpsertOne) Update(set func(*AccountMonitorUpsert)) *AccountMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountMonitorUpsertOne) SetUpdatedAt(v time.Time) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateUpdatedAt() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountMonitorUpsertOne) SetAccountID(v int64) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateAccountID() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountMonitorUpsertOne) SetProvider(v accountmonitor.Provider) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateProvider() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *AccountMonitorUpsertOne) SetModel(v string) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateModel() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateModel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AccountMonitorUpsertOne) SetEnabled(v bool) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateEnabled() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *AccountMonitorUpsertOne) SetIntervalSeconds(v int) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *AccountMonitorUpsertOne) AddIntervalSeconds(v int) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateIntervalSeconds() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (u *AccountMonitorUpsertOne) SetJitterSeconds(v int) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetJitterSeconds(v)
	})
}

// AddJitterSeconds adds v to the "jitter_seconds" field.
func (u *AccountMonitorUpsertOne) AddJitterSeconds(v int) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddJitterSeconds(v)
	})
}

// UpdateJitterSeconds sets the "jitter_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateJitterSeconds() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateJitterSeconds()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountMonitorUpsertOne) SetLastCheckedAt(v time.Time) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateLastCheckedAt() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountMonitorUpsertOne) ClearLastCheckedAt() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountMonitorUpsertOne) SetCreatedBy(v int64) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountMonitorUpsertOne) AddCreatedBy(v int64) *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountMonitorUpsertOne) UpdateCreatedBy() *AccountMonitorUpsertOne {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *AccountMonitorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountMonitorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountMonitorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountMonitorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountMonitorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountMonitorCreateBulk is the builder for creating many AccountMonitor entities in bulk.
type AccountMonitorCreateBulk struct {
	config
	err      error
	builders []*AccountMonitorCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountMonitor entities in the database.
func (_c *AccountMonitorCreateBulk) Save(ctx context.Context) ([]*AccountMonitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountMonitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountMonitorCreateBulk) SaveX(ctx context.Context) []*AccountMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountMonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountMonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountMonitor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountMonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountMonitorCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountMonitorUpsertBulk {
	_c.conflict = opts
	return &AccountMonitorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountMonitorCreateBulk) OnConflictColumns(columns ...string) *AccountMonitorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountMonitorUpsertBulk{
		create: _c,
	}
}

// AccountMonitorUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountMonitor nodes.
type AccountMonitorUpsertBulk struct {
	create *AccountMonitorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountMonitorUpsertBulk) UpdateNewValues() *AccountMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountmonitor.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountMonitor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountMonitorUpsertBulk) Ignore() *AccountMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountMonitorUpsertBulk) DoNothing() *AccountMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountMonitorCreateBulk.OnConflict
// documentation for more info.
func (u *AccountMonitorUpsertBulk) Update(set func(*AccountMonitorUpsert)) *AccountMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountMonitorUpsertBulk) SetUpdatedAt(v time.Time) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateUpdatedAt() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountMonitorUpsertBulk) SetAccountID(v int64) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateAccountID() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountMonitorUpsertBulk) SetProvider(v accountmonitor.Provider) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateProvider() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *AccountMonitorUpsertBulk) SetModel(v string) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateModel() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateModel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AccountMonitorUpsertBulk) SetEnabled(v bool) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateEnabled() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *AccountMonitorUpsertBulk) SetIntervalSeconds(v int) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *AccountMonitorUpsertBulk) AddIntervalSeconds(v int) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateIntervalSeconds() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetJitterSeconds sets the "jitter_seconds" field.
func (u *AccountMonitorUpsertBulk) SetJitterSeconds(v int) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetJitterSeconds(v)
	})
}

// AddJitterSeconds adds v to the "jitter_seconds" field.
func (u *AccountMonitorUpsertBulk) AddJitterSeconds(v int) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddJitterSeconds(v)
	})
}

// UpdateJitterSeconds sets the "jitter_seconds" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateJitterSeconds() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateJitterSeconds()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountMonitorUpsertBulk) SetLastCheckedAt(v time.Time) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateLastCheckedAt() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountMonitorUpsertBulk) ClearLastCheckedAt() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountMonitorUpsertBulk) SetCreatedBy(v int64) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountMonitorUpsertBulk) AddCreatedBy(v int64) *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountMonitorUpsertBulk) UpdateCreatedBy() *AccountMonitorUpsertBulk {
	return u.Update(func(s *AccountMonitorUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *AccountMonitorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountMonitorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountMonitorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountMonitorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
