// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketread"
)

// TicketRead is the model entity for the TicketRead schema.
type TicketRead struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// 已读主体: user, admin
	ActorType string `json:"actor_type,omitempty"`
	// 已读主体用户ID
	ActorID int64 `json:"actor_id,omitempty"`
	// 最后已读消息ID
	LastReadMessageID *int64 `json:"last_read_message_id,omitempty"`
	// 最后已读时间
	ReadAt time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketReadQuery when eager-loading is set.
	Edges        TicketReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketReadEdges holds the relations/edges for other nodes in the graph.
type TicketReadEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketReadEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketread.FieldID, ticketread.FieldTicketID, ticketread.FieldActorID, ticketread.FieldLastReadMessageID:
			values[i] = new(sql.NullInt64)
		case ticketread.FieldActorType:
			values[i] = new(sql.NullString)
		case ticketread.FieldReadAt, ticketread.FieldCreatedAt, ticketread.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketRead fields.
func (_m *TicketRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticketread.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case ticketread.FieldActorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_type", values[i])
			} else if value.Valid {
				_m.ActorType = value.String
			}
		case ticketread.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.Int64
			}
		case ticketread.FieldLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_message_id", values[i])
			} else if value.Valid {
				_m.LastReadMessageID = new(int64)
				*_m.LastReadMessageID = value.Int64
			}
		case ticketread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = value.Time
			}
		case ticketread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticketread.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketRead.
// This includes values selected through modifiers, order, etc.
func (_m *TicketRead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketRead entity.
func (_m *TicketRead) QueryTicket() *TicketQuery {
	return NewTicketReadClient(_m.config).QueryTicket(_m)
}

// Update returns a builder for updating this TicketRead.
// Note that you need to call TicketRead.Unwrap() before calling this method if this TicketRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketRead) Update() *TicketReadUpdateOne {
	return NewTicketReadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketRead) Unwrap() *TicketRead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketRead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketRead) String() string {
	var builder strings.Builder
	builder.WriteString("TicketRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("actor_type=")
	builder.WriteString(_m.ActorType)
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorID))
	builder.WriteString(", ")
	if v := _m.LastReadMessageID; v != nil {
		builder.WriteString("last_read_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(_m.ReadAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketReads is a parsable slice of TicketRead.
type TicketReads []*TicketRead
