// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 工单编号
	TicketNo string `json:"ticket_no,omitempty"`
	// 提交用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 提交用户邮箱快照
	UserEmail string `json:"user_email,omitempty"`
	// 提交用户名称快照
	UserName string `json:"user_name,omitempty"`
	// 工单标题
	Subject string `json:"subject,omitempty"`
	// 分类: general, billing, usage, technical, account
	Category string `json:"category,omitempty"`
	// 优先级: low, normal, high, urgent
	Priority string `json:"priority,omitempty"`
	// 状态: open, pending, resolved, closed
	Status string `json:"status,omitempty"`
	// 来源
	Source string `json:"source,omitempty"`
	// 工单模板标识
	TemplateKey string `json:"template_key,omitempty"`
	// 关联上下文类型
	ContextType string `json:"context_type,omitempty"`
	// 关联上下文ID
	ContextID string `json:"context_id,omitempty"`
	// 动态模板字段和上下文快照
	ContextData map[string]interface{} `json:"context_data,omitempty"`
	// 指派管理员ID
	AssigneeID *int64 `json:"assignee_id,omitempty"`
	// 升级给超级管理员时间
	EscalatedAt *time.Time `json:"escalated_at,omitempty"`
	// 升级操作人ID
	EscalatedBy *int64 `json:"escalated_by,omitempty"`
	// 升级原因
	EscalationReason string `json:"escalation_reason,omitempty"`
	// SLA响应截止时间
	SLADueAt *time.Time `json:"sla_due_at,omitempty"`
	// SLA催办通知时间
	SLARemindedAt *time.Time `json:"sla_reminded_at,omitempty"`
	// 最后消息时间
	LastMessageAt time.Time `json:"last_message_at,omitempty"`
	// 最后用户回复时间
	LastUserMessageAt *time.Time `json:"last_user_message_at,omitempty"`
	// 最后管理员回复时间
	LastAdminMessageAt *time.Time `json:"last_admin_message_at,omitempty"`
	// 解决时间
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// 关闭时间
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges        TicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*TicketMessage `json:"messages,omitempty"`
	// Reads holds the value of the reads edge.
	Reads []*TicketRead `json:"reads,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) MessagesOrErr() ([]*TicketMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// ReadsOrErr returns the Reads value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) ReadsOrErr() ([]*TicketRead, error) {
	if e.loadedTypes[1] {
		return e.Reads, nil
	}
	return nil, &NotLoadedError{edge: "reads"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldContextData:
			values[i] = new([]byte)
		case ticket.FieldID, ticket.FieldUserID, ticket.FieldAssigneeID, ticket.FieldEscalatedBy:
			values[i] = new(sql.NullInt64)
		case ticket.FieldTicketNo, ticket.FieldUserEmail, ticket.FieldUserName, ticket.FieldSubject, ticket.FieldCategory, ticket.FieldPriority, ticket.FieldStatus, ticket.FieldSource, ticket.FieldTemplateKey, ticket.FieldContextType, ticket.FieldContextID, ticket.FieldEscalationReason:
			values[i] = new(sql.NullString)
		case ticket.FieldEscalatedAt, ticket.FieldSLADueAt, ticket.FieldSLARemindedAt, ticket.FieldLastMessageAt, ticket.FieldLastUserMessageAt, ticket.FieldLastAdminMessageAt, ticket.FieldResolvedAt, ticket.FieldClosedAt, ticket.FieldCreatedAt, ticket.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (_m *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticket.FieldTicketNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_no", values[i])
			} else if value.Valid {
				_m.TicketNo = value.String
			}
		case ticket.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case ticket.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case ticket.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case ticket.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case ticket.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case ticket.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case ticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ticket.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case ticket.FieldTemplateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_key", values[i])
			} else if value.Valid {
				_m.TemplateKey = value.String
			}
		case ticket.FieldContextType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_type", values[i])
			} else if value.Valid {
				_m.ContextType = value.String
			}
		case ticket.FieldContextID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_id", values[i])
			} else if value.Valid {
				_m.ContextID = value.String
			}
		case ticket.FieldContextData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field context_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContextData); err != nil {
					return fmt.Errorf("unmarshal field context_data: %w", err)
				}
			}
		case ticket.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = new(int64)
				*_m.AssigneeID = value.Int64
			}
		case ticket.FieldEscalatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field escalated_at", values[i])
			} else if value.Valid {
				_m.EscalatedAt = new(time.Time)
				*_m.EscalatedAt = value.Time
			}
		case ticket.FieldEscalatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field escalated_by", values[i])
			} else if value.Valid {
				_m.EscalatedBy = new(int64)
				*_m.EscalatedBy = value.Int64
			}
		case ticket.FieldEscalationReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field escalation_reason", values[i])
			} else if value.Valid {
				_m.EscalationReason = value.String
			}
		case ticket.FieldSLADueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sla_due_at", values[i])
			} else if value.Valid {
				_m.SLADueAt = new(time.Time)
				*_m.SLADueAt = value.Time
			}
		case ticket.FieldSLARemindedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sla_reminded_at", values[i])
			} else if value.Valid {
				_m.SLARemindedAt = new(time.Time)
				*_m.SLARemindedAt = value.Time
			}
		case ticket.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = value.Time
			}
		case ticket.FieldLastUserMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_user_message_at", values[i])
			} else if value.Valid {
				_m.LastUserMessageAt = new(time.Time)
				*_m.LastUserMessageAt = value.Time
			}
		case ticket.FieldLastAdminMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_admin_message_at", values[i])
			} else if value.Valid {
				_m.LastAdminMessageAt = new(time.Time)
				*_m.LastAdminMessageAt = value.Time
			}
		case ticket.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case ticket.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case ticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (_m *Ticket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the Ticket entity.
func (_m *Ticket) QueryMessages() *TicketMessageQuery {
	return NewTicketClient(_m.config).QueryMessages(_m)
}

// QueryReads queries the "reads" edge of the Ticket entity.
func (_m *Ticket) QueryReads() *TicketReadQuery {
	return NewTicketClient(_m.config).QueryReads(_m)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ticket) Unwrap() *Ticket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_no=")
	builder.WriteString(_m.TicketNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("template_key=")
	builder.WriteString(_m.TemplateKey)
	builder.WriteString(", ")
	builder.WriteString("context_type=")
	builder.WriteString(_m.ContextType)
	builder.WriteString(", ")
	builder.WriteString("context_id=")
	builder.WriteString(_m.ContextID)
	builder.WriteString(", ")
	builder.WriteString("context_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContextData))
	builder.WriteString(", ")
	if v := _m.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EscalatedAt; v != nil {
		builder.WriteString("escalated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EscalatedBy; v != nil {
		builder.WriteString("escalated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("escalation_reason=")
	builder.WriteString(_m.EscalationReason)
	builder.WriteString(", ")
	if v := _m.SLADueAt; v != nil {
		builder.WriteString("sla_due_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SLARemindedAt; v != nil {
		builder.WriteString("sla_reminded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_message_at=")
	builder.WriteString(_m.LastMessageAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastUserMessageAt; v != nil {
		builder.WriteString("last_user_message_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastAdminMessageAt; v != nil {
		builder.WriteString("last_admin_message_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
