// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// Upstream is the model entity for the Upstream schema.
type Upstream struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind upstream.Kind `json:"kind,omitempty"`
	// Credentials holds the value of the "credentials" field.
	Credentials map[string]interface{} `json:"credentials,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// Status holds the value of the "status" field.
	Status upstream.Status `json:"status,omitempty"`
	// LastProbeAt holds the value of the "last_probe_at" field.
	LastProbeAt *time.Time `json:"last_probe_at,omitempty"`
	// LastProbeError holds the value of the "last_probe_error" field.
	LastProbeError *string `json:"last_probe_error,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamQuery when eager-loading is set.
	Edges        UpstreamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamEdges holds the relations/edges for other nodes in the graph.
type UpstreamEdges struct {
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Upstream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstream.FieldCredentials, upstream.FieldMetadata:
			values[i] = new([]byte)
		case upstream.FieldID, upstream.FieldProxyID:
			values[i] = new(sql.NullInt64)
		case upstream.FieldName, upstream.FieldBaseURL, upstream.FieldKind, upstream.FieldStatus, upstream.FieldLastProbeError:
			values[i] = new(sql.NullString)
		case upstream.FieldCreatedAt, upstream.FieldUpdatedAt, upstream.FieldDeletedAt, upstream.FieldLastProbeAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Upstream fields.
func (_m *Upstream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstream.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstream.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstream.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstream.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case upstream.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstream.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstream.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = upstream.Kind(value.String)
			}
		case upstream.FieldCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Credentials); err != nil {
					return fmt.Errorf("unmarshal field credentials: %w", err)
				}
			}
		case upstream.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case upstream.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = upstream.Status(value.String)
			}
		case upstream.FieldLastProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_at", values[i])
			} else if value.Valid {
				_m.LastProbeAt = new(time.Time)
				*_m.LastProbeAt = value.Time
			}
		case upstream.FieldLastProbeError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_error", values[i])
			} else if value.Valid {
				_m.LastProbeError = new(string)
				*_m.LastProbeError = value.String
			}
		case upstream.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Upstream.
// This includes values selected through modifiers, order, etc.
func (_m *Upstream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxy queries the "proxy" edge of the Upstream entity.
func (_m *Upstream) QueryProxy() *ProxyQuery {
	return NewUpstreamClient(_m.config).QueryProxy(_m)
}

// QueryAccounts queries the "accounts" edge of the Upstream entity.
func (_m *Upstream) QueryAccounts() *AccountQuery {
	return NewUpstreamClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this Upstream.
// Note that you need to call Upstream.Unwrap() before calling this method if this Upstream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Upstream) Update() *UpstreamUpdateOne {
	return NewUpstreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Upstream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Upstream) Unwrap() *Upstream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Upstream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Upstream) String() string {
	var builder strings.Builder
	builder.WriteString("Upstream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("credentials=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credentials))
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.LastProbeAt; v != nil {
		builder.WriteString("last_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastProbeError; v != nil {
		builder.WriteString("last_probe_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// Upstreams is a parsable slice of Upstream.
type Upstreams []*Upstream
