// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// UpstreamCreate is the builder for creating a Upstream entity.
type UpstreamCreate struct {
	config
	mutation *UpstreamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamCreate) SetCreatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableCreatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamCreate) SetUpdatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamCreate) SetDeletedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableDeletedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamCreate) SetName(v string) *UpstreamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamCreate) SetBaseURL(v string) *UpstreamCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *UpstreamCreate) SetKind(v upstream.Kind) *UpstreamCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableKind(v *upstream.Kind) *UpstreamCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetCredentials sets the "credentials" field.
func (_c *UpstreamCreate) SetCredentials(v map[string]interface{}) *UpstreamCreate {
	_c.mutation.SetCredentials(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *UpstreamCreate) SetProxyID(v int64) *UpstreamCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableProxyID(v *int64) *UpstreamCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamCreate) SetStatus(v upstream.Status) *UpstreamCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableStatus(v *upstream.Status) *UpstreamCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_c *UpstreamCreate) SetLastProbeAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetLastProbeAt(v)
	return _c
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLastProbeAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetLastProbeAt(*v)
	}
	return _c
}

// SetLastProbeError sets the "last_probe_error" field.
func (_c *UpstreamCreate) SetLastProbeError(v string) *UpstreamCreate {
	_c.mutation.SetLastProbeError(v)
	return _c
}

// SetNillableLastProbeError sets the "last_probe_error" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLastProbeError(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetLastProbeError(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UpstreamCreate) SetMetadata(v map[string]interface{}) *UpstreamCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *UpstreamCreate) SetProxy(v *Proxy) *UpstreamCreate {
	return _c.SetProxyID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *UpstreamCreate) AddAccountIDs(ids ...int64) *UpstreamCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *UpstreamCreate) AddAccounts(v ...*Account) *UpstreamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the UpstreamMutation object of the builder.
func (_c *UpstreamCreate) Mutation() *UpstreamMutation {
	return _c.mutation
}

// Save creates the Upstream in the database.
func (_c *UpstreamCreate) Save(ctx context.Context) (*Upstream, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamCreate) SaveX(ctx context.Context) *Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstream.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstream.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := upstream.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		if upstream.DefaultCredentials == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultCredentials (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultCredentials()
		_c.mutation.SetCredentials(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstream.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		if upstream.DefaultMetadata == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultMetadata (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Upstream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Upstream.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Upstream.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "Upstream.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Upstream.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := upstream.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Upstream.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`ent: missing required field "Upstream.credentials"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Upstream.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstream.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Upstream.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Upstream.metadata"`)}
	}
	return nil
}

func (_c *UpstreamCreate) sqlSave(ctx context.Context) (*Upstream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamCreate) createSpec() (*Upstream, *sqlgraph.CreateSpec) {
	var (
		_node = &Upstream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstream.Table, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(upstream.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Credentials(); ok {
		_spec.SetField(upstream.FieldCredentials, field.TypeJSON, value)
		_node.Credentials = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstream.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastProbeAt(); ok {
		_spec.SetField(upstream.FieldLastProbeAt, field.TypeTime, value)
		_node.LastProbeAt = &value
	}
	if value, ok := _c.mutation.LastProbeError(); ok {
		_spec.SetField(upstream.FieldLastProbeError, field.TypeString, value)
		_node.LastProbeError = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(upstream.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstream.ProxyTable,
			Columns: []string{upstream.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstream.AccountsTable,
			Columns: []string{upstream.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertOne {
	_c.conflict = opts
	return &UpstreamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflictColumns(columns ...string) *UpstreamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamUpsertOne is the builder for "upsert"-ing
	//  one Upstream node.
	UpstreamUpsertOne struct {
		create *UpstreamCreate
	}

	// UpstreamUpsert is the "OnConflict" setter.
	UpstreamUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsert) SetUpdatedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateUpdatedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsert) SetDeletedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateDeletedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsert) ClearDeletedAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamUpsert) SetName(v string) *UpstreamUpsert {
	u.Set(upstream.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateName() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsert) SetBaseURL(v string) *UpstreamUpsert {
	u.Set(upstream.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateBaseURL() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldBaseURL)
	return u
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsert) SetKind(v upstream.Kind) *UpstreamUpsert {
	u.Set(upstream.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateKind() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldKind)
	return u
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamUpsert) SetCredentials(v map[string]interface{}) *UpstreamUpsert {
	u.Set(upstream.FieldCredentials, v)
	return u
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateCredentials() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldCredentials)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamUpsert) SetProxyID(v int64) *UpstreamUpsert {
	u.Set(upstream.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateProxyID() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamUpsert) ClearProxyID() *UpstreamUpsert {
	u.SetNull(upstream.FieldProxyID)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamUpsert) SetStatus(v upstream.Status) *UpstreamUpsert {
	u.Set(upstream.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateStatus() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldStatus)
	return u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *UpstreamUpsert) SetLastProbeAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldLastProbeAt, v)
	return u
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLastProbeAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLastProbeAt)
	return u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *UpstreamUpsert) ClearLastProbeAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldLastProbeAt)
	return u
}

// SetLastProbeError sets the "last_probe_error" field.
func (u *UpstreamUpsert) SetLastProbeError(v string) *UpstreamUpsert {
	u.Set(upstream.FieldLastProbeError, v)
	return u
}

// UpdateLastProbeError sets the "last_probe_error" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLastProbeError() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLastProbeError)
	return u
}

// ClearLastProbeError clears the value of the "last_probe_error" field.
func (u *UpstreamUpsert) ClearLastProbeError() *UpstreamUpsert {
	u.SetNull(upstream.FieldLastProbeError)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *UpstreamUpsert) SetMetadata(v map[string]interface{}) *UpstreamUpsert {
	u.Set(upstream.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateMetadata() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertOne) UpdateNewValues() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstream.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamUpsertOne) Ignore() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertOne) DoNothing() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreate.OnConflict
// documentation for more info.
func (u *UpstreamUpsertOne) Update(set func(*UpstreamUpsert)) *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertOne) SetUpdatedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateUpdatedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertOne) SetDeletedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertOne) ClearDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertOne) SetName(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateName() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertOne) SetBaseURL(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateBaseURL() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsertOne) SetKind(v upstream.Kind) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateKind() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateKind()
	})
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamUpsertOne) SetCredentials(v map[string]interface{}) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateCredentials() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateCredentials()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamUpsertOne) SetProxyID(v int64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateProxyID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamUpsertOne) ClearProxyID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamUpsertOne) SetStatus(v upstream.Status) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateStatus() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateStatus()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *UpstreamUpsertOne) SetLastProbeAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLastProbeAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *UpstreamUpsertOne) ClearLastProbeAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastProbeError sets the "last_probe_error" field.
func (u *UpstreamUpsertOne) SetLastProbeError(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastProbeError(v)
	})
}

// UpdateLastProbeError sets the "last_probe_error" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLastProbeError() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastProbeError()
	})
}

// ClearLastProbeError clears the value of the "last_probe_error" field.
func (u *UpstreamUpsertOne) ClearLastProbeError() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastProbeError()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UpstreamUpsertOne) SetMetadata(v map[string]interface{}) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateMetadata() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamCreateBulk is the builder for creating many Upstream entities in bulk.
type UpstreamCreateBulk struct {
	config
	err      error
	builders []*UpstreamCreate
	conflict []sql.ConflictOption
}

// Save creates the Upstream entities in the database.
func (_c *UpstreamCreateBulk) Save(ctx context.Context) ([]*Upstream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Upstream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamCreateBulk) SaveX(ctx context.Context) []*Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertBulk {
	_c.conflict = opts
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflictColumns(columns ...string) *UpstreamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// UpstreamUpsertBulk is the builder for "upsert"-ing
// a bulk of Upstream nodes.
type UpstreamUpsertBulk struct {
	create *UpstreamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) UpdateNewValues() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstream.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) Ignore() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertBulk) DoNothing() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamUpsertBulk) Update(set func(*UpstreamUpsert)) *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateUpdatedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertBulk) SetDeletedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertBulk) ClearDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertBulk) SetName(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateName() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertBulk) SetBaseURL(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateBaseURL() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsertBulk) SetKind(v upstream.Kind) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateKind() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateKind()
	})
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamUpsertBulk) SetCredentials(v map[string]interface{}) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateCredentials() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateCredentials()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamUpsertBulk) SetProxyID(v int64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateProxyID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamUpsertBulk) ClearProxyID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamUpsertBulk) SetStatus(v upstream.Status) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateStatus() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateStatus()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *UpstreamUpsertBulk) SetLastProbeAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLastProbeAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *UpstreamUpsertBulk) ClearLastProbeAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastProbeError sets the "last_probe_error" field.
func (u *UpstreamUpsertBulk) SetLastProbeError(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastProbeError(v)
	})
}

// UpdateLastProbeError sets the "last_probe_error" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLastProbeError() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastProbeError()
	})
}

// ClearLastProbeError clears the value of the "last_probe_error" field.
func (u *UpstreamUpsertBulk) ClearLastProbeError() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastProbeError()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UpstreamUpsertBulk) SetMetadata(v map[string]interface{}) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateMetadata() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
