// Code generated by ent, DO NOT EDIT.

package ticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// SenderType applies equality check predicate on the "sender_type" field. It's identical to SenderTypeEQ.
func SenderType(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderName, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldVisibility, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldBody, v))
}

// EditedAt applies equality check predicate on the "edited_at" field. It's identical to EditedAtEQ.
func EditedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldEditedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// SenderTypeEQ applies the EQ predicate on the "sender_type" field.
func SenderTypeEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderTypeNEQ applies the NEQ predicate on the "sender_type" field.
func SenderTypeNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldSenderType, v))
}

// SenderTypeIn applies the In predicate on the "sender_type" field.
func SenderTypeIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldSenderType, vs...))
}

// SenderTypeNotIn applies the NotIn predicate on the "sender_type" field.
func SenderTypeNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldSenderType, vs...))
}

// SenderTypeGT applies the GT predicate on the "sender_type" field.
func SenderTypeGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldSenderType, v))
}

// SenderTypeGTE applies the GTE predicate on the "sender_type" field.
func SenderTypeGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldSenderType, v))
}

// SenderTypeLT applies the LT predicate on the "sender_type" field.
func SenderTypeLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldSenderType, v))
}

// SenderTypeLTE applies the LTE predicate on the "sender_type" field.
func SenderTypeLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldSenderType, v))
}

// SenderTypeContains applies the Contains predicate on the "sender_type" field.
func SenderTypeContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldSenderType, v))
}

// SenderTypeHasPrefix applies the HasPrefix predicate on the "sender_type" field.
func SenderTypeHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldSenderType, v))
}

// SenderTypeHasSuffix applies the HasSuffix predicate on the "sender_type" field.
func SenderTypeHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldSenderType, v))
}

// SenderTypeEqualFold applies the EqualFold predicate on the "sender_type" field.
func SenderTypeEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldSenderType, v))
}

// SenderTypeContainsFold applies the ContainsFold predicate on the "sender_type" field.
func SenderTypeContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldSenderType, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldSenderID, v))
}

// SenderIDIsNil applies the IsNil predicate on the "sender_id" field.
func SenderIDIsNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIsNull(FieldSenderID))
}

// SenderIDNotNil applies the NotNil predicate on the "sender_id" field.
func SenderIDNotNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotNull(FieldSenderID))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldSenderName, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldVisibility, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldBody, v))
}

// EditedAtEQ applies the EQ predicate on the "edited_at" field.
func EditedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldEditedAt, v))
}

// EditedAtNEQ applies the NEQ predicate on the "edited_at" field.
func EditedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldEditedAt, v))
}

// EditedAtIn applies the In predicate on the "edited_at" field.
func EditedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldEditedAt, vs...))
}

// EditedAtNotIn applies the NotIn predicate on the "edited_at" field.
func EditedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldEditedAt, vs...))
}

// EditedAtGT applies the GT predicate on the "edited_at" field.
func EditedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldEditedAt, v))
}

// EditedAtGTE applies the GTE predicate on the "edited_at" field.
func EditedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldEditedAt, v))
}

// EditedAtLT applies the LT predicate on the "edited_at" field.
func EditedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldEditedAt, v))
}

// EditedAtLTE applies the LTE predicate on the "edited_at" field.
func EditedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldEditedAt, v))
}

// EditedAtIsNil applies the IsNil predicate on the "edited_at" field.
func EditedAtIsNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIsNull(FieldEditedAt))
}

// EditedAtNotNil applies the NotNil predicate on the "edited_at" field.
func EditedAtNotNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotNull(FieldEditedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.NotPredicates(p))
}
