import json
import os
import subprocess
import unittest


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OVERLAY_POLICY_PATH = os.path.join(REPO_ROOT, "tools", "upstream_overlay_policy.json")
PRISTINE_PATHS = (
    "backend/internal/domain/constants.go",
    "backend/internal/handler/handler.go",
    "backend/internal/handler/wire.go",
    "backend/internal/handler/dto/credentials_redact.go",
    "backend/internal/handler/ops_error_logger.go",
    "backend/internal/handler/subscription_handler.go",
    "backend/internal/handler/user_handler.go",
    "backend/internal/pkg/apicompat/types.go",
    "backend/internal/pkg/ctxkey/ctxkey.go",
    "backend/internal/pkg/googleapi/status.go",
    "backend/internal/payment/types.go",
    "backend/internal/repository/migrations_runner.go",
    "backend/internal/repository/wire.go",
    "backend/internal/repository/error_translate.go",
    "backend/internal/server/routes/auth.go",
    "backend/internal/server/routes/payment.go",
    "backend/internal/server/http.go",
    "backend/internal/server/router.go",
    "backend/internal/handler/admin/subscription_handler.go",
    "backend/internal/service/channel_monitor_validate.go",
    "backend/internal/service/wire.go",
    "backend/internal/service/channel_monitor_aggregator.go",
    "backend/internal/service/http_upstream_port.go",
    "backend/internal/service/model_rate_limit.go",
    "backend/internal/service/openai_account_runtime_block_fastpath.go",
    "backend/internal/service/payment_config_providers.go",
    "backend/internal/service/scheduler_outbox.go",
    "backend/internal/service/temp_unsched.go",
    "backend/internal/service/usage_log_helpers.go",
    "frontend/src/api/admin/index.ts",
    "frontend/package.json",
    "frontend/src/api/admin/accounts.ts",
    "frontend/src/api/admin/channelMonitor.ts",
    "frontend/src/api/admin/groups.ts",
    "frontend/src/api/admin/ops.ts",
    "frontend/src/api/admin/payment.ts",
    "frontend/src/api/admin/settings.ts",
    "frontend/src/api/admin/subscriptions.ts",
    "frontend/src/api/admin/users.ts",
    "frontend/src/api/__tests__/user.spec.ts",
    "frontend/src/api/channelMonitor.ts",
    "frontend/src/api/channels.ts",
    "frontend/src/api/groups.ts",
    "frontend/src/api/index.ts",
    "frontend/src/api/keys.ts",
    "frontend/src/api/payment.ts",
    "frontend/src/api/subscriptions.ts",
    "frontend/src/api/usage.ts",
    "frontend/src/api/user.ts",
    "frontend/src/components/TurnstileWidget.vue",
    "frontend/src/components/Guide/steps.ts",
    "frontend/src/components/account/AccountGroupsCell.vue",
    "frontend/src/components/account/AccountStatsModal.vue",
    "frontend/src/components/account/AccountTestModal.vue",
    "frontend/src/components/account/CreateAccountModal.vue",
    "frontend/src/components/account/EditAccountModal.vue",
    "frontend/src/components/account/ReAuthAccountModal.vue",
    "frontend/src/components/account/ModelWhitelistSelector.vue",
    "frontend/src/components/account/__tests__/AccountUsageCell.spec.ts",
    "frontend/src/components/account/__tests__/AccountStatusIndicator.spec.ts",
    "frontend/src/components/account/__tests__/EditAccountModal.spec.ts",
    "frontend/src/components/account/__tests__/UsageProgressBar.spec.ts",
    "frontend/src/components/account/__tests__/AccountTestModal.spec.ts",
    "frontend/src/components/admin/account/ImportDataModal.vue",
    "frontend/src/components/admin/account/AccountTestModal.vue",
    "frontend/src/components/admin/monitor/MonitorKeyPickerDialog.vue",
    "frontend/src/components/admin/AdminComplianceDialog.vue",
    "frontend/src/components/admin/payment/AdminOrderDetail.vue",
    "frontend/src/components/admin/payment/AdminOrderTable.vue",
    "frontend/src/components/admin/payment/OrderStatsCards.vue",
    "frontend/src/components/admin/payment/PaymentMethodChart.vue",
    "frontend/src/components/admin/announcements/AnnouncementTargetingEditor.vue",
    "frontend/src/components/admin/usage/UsageStatsCards.vue",
    "frontend/src/components/admin/usage/UsageFilters.vue",
    "frontend/src/components/admin/usage/UsageTable.vue",
    "frontend/src/components/admin/usage/__tests__/UsageFilters.spec.ts",
    "frontend/src/components/admin/usage/__tests__/UsageTable.spec.ts",
    "frontend/src/components/admin/usage/__tests__/UsageStatsCards.spec.ts",
    "frontend/src/components/auth/EmailOAuthButtons.vue",
    "frontend/src/components/auth/LoginAgreementPrompt.vue",
    "frontend/src/components/auth/OidcOAuthSection.vue",
    "frontend/src/components/auth/TotpLoginModal.vue",
    "frontend/src/components/channels/AvailableChannelsTable.vue",
    "frontend/src/components/channels/PricingRow.vue",
    "frontend/src/components/channels/SupportedModelChip.vue",
    "frontend/src/components/charts/__tests__/GroupDistributionChart.spec.ts",
    "frontend/src/components/charts/__tests__/ModelDistributionChart.spec.ts",
    "frontend/src/components/common/AnnouncementBell.vue",
    "frontend/src/components/common/AnnouncementPopup.vue",
    "frontend/src/components/common/BaseDialog.vue",
    "frontend/src/components/common/DataTable.vue",
    "frontend/src/components/common/DateRangePicker.vue",
    "frontend/src/components/common/EmptyState.vue",
    "frontend/src/components/common/GroupBadge.vue",
    "frontend/src/components/common/GroupOptionItem.vue",
    "frontend/src/components/common/GroupSelector.vue",
    "frontend/src/components/common/HelpTooltip.vue",
    "frontend/src/components/common/Input.vue",
    "frontend/src/components/common/Pagination.vue",
    "frontend/src/components/common/Select.vue",
    "frontend/src/components/common/SubscriptionProgressMini.vue",
    "frontend/src/components/common/Toast.vue",
    "frontend/src/components/common/types.ts",
    "frontend/src/components/common/VersionBadge.vue",
    "frontend/src/components/keys/UseKeyModal.vue",
    "frontend/src/components/keys/__tests__/EndpointPopover.spec.ts",
    "frontend/src/components/keys/__tests__/UseKeyModal.spec.ts",
    "frontend/src/components/layout/AuthLayout.vue",
    "frontend/src/components/layout/AppHeader.vue",
    "frontend/src/components/layout/AppLayout.vue",
    "frontend/src/components/layout/AppSidebar.vue",
    "frontend/src/components/layout/TablePageLayout.vue",
    "frontend/src/components/layout/index.ts",
    "frontend/src/components/layout/__tests__/AppSidebar.spec.ts",
    "frontend/src/components/layout/__tests__/docUrlSanitization.spec.ts",
    "frontend/src/components/layout/__tests__/siteLogoSanitization.spec.ts",
    "frontend/src/components/payment/PaymentQRDialog.vue",
    "frontend/src/components/payment/StripePaymentInline.vue",
    "frontend/src/components/payment/currency.ts",
    "frontend/src/components/payment/__tests__/PaymentQRDialog.spec.ts",
    "frontend/src/components/payment/__tests__/providerConfig.spec.ts",
    "frontend/src/components/user/MonitorDetailDialog.vue",
    "frontend/src/components/user/PlatformCostCell.vue",
    "frontend/src/components/user/PlatformUsageBreakdown.vue",
    "frontend/src/components/user/UserAttributesConfigModal.vue",
    "frontend/src/components/user/UserPlatformQuotaCell.vue",
    "frontend/src/components/user/__tests__/UserPlatformQuotaCell.spec.ts",
    "frontend/src/components/user/monitor/MonitorAvailabilityRow.vue",
    "frontend/src/components/user/monitor/MonitorCard.vue",
    "frontend/src/components/user/monitor/MonitorCardGrid.vue",
    "frontend/src/components/user/monitor/MonitorHero.vue",
    "frontend/src/components/user/monitor/MonitorMetricPair.vue",
    "frontend/src/components/user/monitor/MonitorTimeline.vue",
    "frontend/src/components/user/monitor/ProviderIcon.vue",
    "frontend/src/components/user/profile/ProfileAvatarCard.vue",
    "frontend/src/components/user/profile/__tests__/ProfileAvatarCard.spec.ts",
    "frontend/src/components/user/profile/ProfileBalanceNotifyCard.vue",
    "frontend/src/components/user/profile/ProfileEditForm.vue",
    "frontend/src/components/user/profile/ProfileIdentityBindingsSection.vue",
    "frontend/src/components/user/profile/__tests__/ProfileIdentityBindingsSection.spec.ts",
    "frontend/src/components/user/profile/ProfileInfoCard.vue",
    "frontend/src/components/user/profile/__tests__/ProfileInfoCard.spec.ts",
    "frontend/src/components/user/profile/ProfilePasswordForm.vue",
    "frontend/src/components/user/profile/__tests__/ProfilePasswordForm.spec.ts",
    "frontend/src/components/user/profile/ProfileTotpCard.vue",
    "frontend/src/components/user/profile/TotpDisableDialog.vue",
    "frontend/src/components/user/profile/TotpSetupModal.vue",
    "frontend/src/components/user/profile/__tests__/totp-timer-cleanup.spec.ts",
    "frontend/src/components/user/dashboard/UserDashboardCharts.vue",
    "frontend/src/components/user/dashboard/UserDashboardQuickActions.vue",
    "frontend/src/components/user/dashboard/UserDashboardRecentUsage.vue",
    "frontend/src/components/user/dashboard/UserDashboardStats.vue",
    "frontend/src/i18n/index.ts",
    "frontend/src/i18n/locales/en/index.ts",
    "frontend/src/i18n/locales/zh/index.ts",
    "frontend/src/stores/index.ts",
    "frontend/src/stores/__tests__/app.spec.ts",
    "frontend/src/styles/onboarding.css",
    "frontend/src/composables/__tests__/useModelWhitelist.spec.ts",
    "frontend/src/composables/useOnboardingTour.ts",
    "frontend/src/composables/useChannelMonitorFormat.ts",
    "frontend/src/composables/usePersistedPageSize.ts",
    "frontend/src/composables/useTableLoader.ts",
    "frontend/src/utils/ccswitchImport.ts",
    "frontend/src/utils/billingMode.ts",
    "frontend/src/utils/embedded-url.ts",
    "frontend/src/utils/formatters.ts",
    "frontend/src/utils/platformColors.ts",
    "frontend/src/utils/__tests__/ccswitchImport.spec.ts",
    "frontend/src/utils/pricing.ts",
    "frontend/src/views/HomeView.vue",
    "frontend/src/views/KeyUsageView.vue",
    "frontend/src/views/__tests__/KeyUsageView.spec.ts",
    "frontend/src/views/NotFoundView.vue",
    "frontend/src/router/index.ts",
    "frontend/src/router/__tests__/feature-access.spec.ts",
    "frontend/src/router/__tests__/wechat-route.spec.ts",
    "frontend/src/router/meta.d.ts",
    "frontend/src/App.vue",
    "frontend/src/main.ts",
    "frontend/src/style.css",
    "frontend/src/views/admin/ops/components/OpsEmailNotificationCard.vue",
    "frontend/src/views/admin/ops/components/OpsDashboardSkeleton.vue",
    "frontend/src/views/admin/ops/components/OpsErrorDistributionChart.vue",
    "frontend/src/views/admin/ops/components/OpsErrorTrendChart.vue",
    "frontend/src/views/admin/ops/components/OpsLatencyChart.vue",
    "frontend/src/views/admin/ops/components/OpsOpenAITokenStatsCard.vue",
    "frontend/src/views/admin/ops/components/OpsRuntimeSettingsCard.vue",
    "frontend/src/views/admin/SubscriptionsView.vue",
    "frontend/src/views/admin/SettingsView.vue",
    "frontend/src/views/admin/__tests__/SettingsView.spec.ts",
    "frontend/src/views/admin/GroupsView.vue",
    "frontend/src/views/admin/AccountsView.vue",
    "frontend/src/views/admin/__tests__/AccountsView.bulkEdit.spec.ts",
    "frontend/src/views/admin/__tests__/AccountsView.schedulerScore.spec.ts",
    "frontend/src/views/admin/__tests__/AccountsView.sparkShadow.spec.ts",
    "frontend/src/views/admin/__tests__/AccountsView.usageWindowsHint.spec.ts",
    "frontend/src/components/payment/PaymentMethodSelector.vue",
    "frontend/src/components/payment/__tests__/PaymentMethodSelector.spec.ts",
    "frontend/src/views/admin/UsersView.vue",
    "frontend/src/views/admin/__tests__/UsersView.spec.ts",
    "frontend/src/components/admin/user/UserAllowedGroupsModal.vue",
    "frontend/src/views/admin/RiskControlView.vue",
    "frontend/src/views/admin/ChannelMonitorView.vue",
    "frontend/src/views/admin/orders/AdminOrdersView.vue",
    "frontend/src/views/admin/__tests__/RiskControlView.spec.ts",
    "frontend/src/views/admin/DashboardView.vue",
    "frontend/src/views/admin/ChannelsView.vue",
    "frontend/src/views/admin/ProxiesView.vue",
    "frontend/src/views/admin/RedeemView.vue",
    "frontend/src/views/admin/ops/OpsDashboard.vue",
    "frontend/src/views/admin/AnnouncementsView.vue",
    "frontend/src/views/admin/PromoCodesView.vue",
    "frontend/src/views/admin/UsageView.vue",
    "frontend/src/views/admin/orders/AdminPaymentDashboardView.vue",
    "frontend/src/views/admin/orders/AdminPaymentPlansView.vue",
    "frontend/src/views/admin/BackupView.vue",
    "frontend/src/views/admin/settings/EmailTemplateEditor.vue",
    "frontend/src/views/admin/__tests__/UsageView.spec.ts",
    "frontend/src/views/admin/affiliates/AdminAffiliateRecordsTable.vue",
    "frontend/src/views/admin/affiliates/AdminAffiliateInvitesView.vue",
    "frontend/src/views/admin/affiliates/AdminAffiliateRebatesView.vue",
    "frontend/src/views/admin/affiliates/AdminAffiliateTransfersView.vue",
    "frontend/src/views/admin/groupsModelsList.ts",
    "frontend/src/views/admin/orders/PlanEditDialog.vue",
    "frontend/src/views/admin/orders/__tests__/PlanEditDialog.spec.ts",
    "frontend/src/views/admin/ops/components/OpsAlertEventsCard.vue",
    "frontend/src/views/admin/ops/components/OpsAlertRulesCard.vue",
    "frontend/src/views/admin/ops/components/OpsConcurrencyCard.vue",
    "frontend/src/views/admin/ops/components/OpsDashboardHeader.vue",
    "frontend/src/views/admin/ops/components/OpsErrorDetailModal.vue",
    "frontend/src/views/admin/ops/components/OpsRequestDetailsModal.vue",
    "frontend/src/views/admin/ops/components/OpsSettingsDialog.vue",
    "frontend/src/components/charts/EndpointDistributionChart.vue",
    "frontend/src/components/charts/GroupDistributionChart.vue",
    "frontend/src/components/charts/ModelDistributionChart.vue",
    "frontend/src/components/charts/__tests__/GroupDistributionChart.spec.ts",
    "frontend/src/components/charts/__tests__/ModelDistributionChart.spec.ts",
    "frontend/src/components/admin/account/AccountStatsModal.vue",
    "frontend/src/components/account/SyncFromCrsModal.vue",
    "frontend/src/components/admin/user/UserApiKeysModal.vue",
    "frontend/src/components/payment/PaymentProviderList.vue",
    "frontend/src/components/payment/ProviderCard.vue",
    "frontend/src/components/account/BulkEditAccountModal.vue",
    "frontend/src/components/account/TempUnschedStatusModal.vue",
    "frontend/src/components/admin/account/AccountActionMenu.vue",
    "frontend/src/components/admin/account/AccountBulkActionsBar.vue",
    "frontend/src/components/admin/account/AccountTableActions.vue",
    "frontend/src/components/admin/account/AccountTableFilters.vue",
    "frontend/src/components/admin/account/ReAuthAccountModal.vue",
    "frontend/src/components/admin/account/ScheduledTestsPanel.vue",
    "frontend/src/components/account/__tests__/BulkEditAccountModal.spec.ts",
    "frontend/src/components/admin/account/__tests__/AccountActionMenu.spark_shadow.spec.ts",
    "frontend/src/components/account/AccountQuotaInfo.vue",
    "frontend/src/components/account/UsageProgressBar.vue",
    "frontend/src/components/account/AccountStatusIndicator.vue",
    "frontend/src/components/account/AccountUsageCell.vue",
    "frontend/src/components/account/__tests__/AccountStatusIndicator.spec.ts",
    "frontend/src/components/account/__tests__/AccountUsageCell.spec.ts",
    "frontend/src/components/admin/monitor/MonitorAdvancedRequestConfig.vue",
    "frontend/src/components/admin/monitor/MonitorFiltersBar.vue",
    "frontend/src/components/admin/monitor/MonitorFormDialog.vue",
    "frontend/src/components/user/UserErrorDetailModal.vue",
    "frontend/src/components/user/UserErrorRequestsTable.vue",
    "frontend/src/components/admin/user/UserCreateModal.vue",
    "frontend/src/components/admin/user/UserEditModal.vue",
    "frontend/src/components/admin/user/UserBalanceModal.vue",
    "frontend/src/components/admin/group/GroupRateMultipliersModal.vue",
    "frontend/src/components/auth/PendingOAuthCreateAccountForm.vue",
    "frontend/src/components/auth/WechatOAuthSection.vue",
    "frontend/src/components/auth/__tests__/PendingOAuthCreateAccountForm.spec.ts",
    "frontend/src/components/auth/__tests__/WechatOAuthSection.spec.ts",
    "frontend/src/components/admin/account/__tests__/AccountTestModal.spec.ts",
    "frontend/src/components/admin/payment/__tests__/orderCurrencyDisplay.spec.ts",
    "frontend/src/components/payment/__tests__/SubscriptionPlanCard.spec.ts",
    "frontend/src/components/payment/__tests__/paymentFlow.spec.ts",
    "frontend/src/components/payment/__tests__/providerConfig.spec.ts",
    "frontend/src/components/payment/__tests__/PaymentStatusPanel.spec.ts",
    "frontend/src/views/admin/__tests__/DashboardView.spec.ts",
    "frontend/src/views/admin/__tests__/RedeemView.batchUpdate.spec.ts",
    "frontend/src/views/setup/SetupWizardView.vue",
    "frontend/src/views/auth/LoginView.vue",
    "frontend/src/views/auth/RegisterView.vue",
    "frontend/src/views/auth/EmailVerifyView.vue",
    "frontend/src/views/auth/ForgotPasswordView.vue",
    "frontend/src/views/auth/ResetPasswordView.vue",
    "frontend/src/views/auth/WechatPaymentCallbackView.vue",
    "frontend/src/views/auth/LinuxDoCallbackView.vue",
    "frontend/src/views/auth/WechatCallbackView.vue",
    "frontend/src/views/auth/DingTalkCallbackView.vue",
    "frontend/src/views/auth/DingTalkEmailCompletionView.vue",
    "frontend/src/views/auth/OidcCallbackView.vue",
    "frontend/src/views/auth/OAuthCallbackView.vue",
    "frontend/src/views/auth/__tests__/LinuxDoCallbackView.spec.ts",
    "frontend/src/views/auth/__tests__/WechatCallbackView.spec.ts",
    "frontend/src/views/auth/__tests__/OidcCallbackView.spec.ts",
    "frontend/src/views/auth/__tests__/OAuthCallbackView.spec.ts",
    "frontend/src/views/auth/__tests__/EmailVerifyView.spec.ts",
    "frontend/src/views/auth/__tests__/WechatPaymentCallbackView.spec.ts",
    "frontend/src/views/admin/ops/components/OpsSystemLogTable.vue",
    "frontend/src/views/admin/groupsImagePricing.ts",
    "frontend/src/views/admin/groupsMessagesDispatch.ts",
    "frontend/src/views/admin/__tests__/groupsModelsList.spec.ts",
    "frontend/src/views/admin/__tests__/groupsMessagesDispatch.spec.ts",
    "frontend/src/views/admin/__tests__/groupsImagePricing.spec.ts",
    "frontend/src/views/admin/ops/components/OpsSwitchRateTrendChart.vue",
    "frontend/src/views/admin/ops/components/OpsThroughputTrendChart.vue",
    "frontend/src/views/public/LegalDocumentView.vue",
    "frontend/src/views/user/AvailableChannelsView.vue",
    "frontend/src/views/user/BatchImageGuideView.vue",
    "frontend/src/views/user/CustomPageView.vue",
    "frontend/src/views/user/KeysView.vue",
    "frontend/src/views/user/__tests__/KeysView.spec.ts",
    "frontend/src/views/user/PaymentView.vue",
    "frontend/src/views/user/__tests__/PaymentView.spec.ts",
    "frontend/src/views/user/UsageView.vue",
    "frontend/src/views/user/__tests__/UsageView.spec.ts",
)


def tree_entry_kind(ref, path):
    output = subprocess.check_output(
        ["git", "ls-tree", ref, "--", path],
        cwd=REPO_ROOT,
        text=True,
    ).strip()
    if not output:
        return None
    mode, object_type, _rest = output.split(maxsplit=2)
    return mode, object_type


class UpstreamPristineTest(unittest.TestCase):
    def assert_path_matches_upstream(self, path):
        upstream = subprocess.check_output(
            ["git", "show", f"upstream/main:{path}"],
            cwd=REPO_ROOT,
        )
        with open(os.path.join(REPO_ROOT, path), "rb") as source:
            local = source.read()

        self.assertEqual(
            local,
            upstream,
            "keep local changes in designated overlay or extension files",
        )
        self.assertEqual(
            tree_entry_kind("HEAD", path),
            tree_entry_kind("upstream/main", path),
            "keep official file mode and object type unchanged",
        )

    def test_official_views_stay_pristine(self):
        for path in PRISTINE_PATHS:
            with self.subTest(path=path):
                self.assert_path_matches_upstream(path)

    def test_overlay_fork_sources_stay_pristine(self):
        with open(OVERLAY_POLICY_PATH, encoding="utf-8") as source:
            policy = json.load(source)

        for fork in policy["forks"]:
            path = fork["upstream_path"]
            with self.subTest(path=path):
                self.assert_path_matches_upstream(path)


if __name__ == "__main__":
    unittest.main()
