// Code generated by ent, DO NOT EDIT.

package accountmonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldAccountID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldModel, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldEnabled, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// JitterSeconds applies equality check predicate on the "jitter_seconds" field. It's identical to JitterSecondsEQ.
func JitterSeconds(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldJitterSeconds, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldAccountID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldProvider, vs...))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldContainsFold(FieldModel, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldEnabled, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldIntervalSeconds, v))
}

// JitterSecondsEQ applies the EQ predicate on the "jitter_seconds" field.
func JitterSecondsEQ(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldJitterSeconds, v))
}

// JitterSecondsNEQ applies the NEQ predicate on the "jitter_seconds" field.
func JitterSecondsNEQ(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldJitterSeconds, v))
}

// JitterSecondsIn applies the In predicate on the "jitter_seconds" field.
func JitterSecondsIn(vs ...int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldJitterSeconds, vs...))
}

// JitterSecondsNotIn applies the NotIn predicate on the "jitter_seconds" field.
func JitterSecondsNotIn(vs ...int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldJitterSeconds, vs...))
}

// JitterSecondsGT applies the GT predicate on the "jitter_seconds" field.
func JitterSecondsGT(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldJitterSeconds, v))
}

// JitterSecondsGTE applies the GTE predicate on the "jitter_seconds" field.
func JitterSecondsGTE(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldJitterSeconds, v))
}

// JitterSecondsLT applies the LT predicate on the "jitter_seconds" field.
func JitterSecondsLT(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldJitterSeconds, v))
}

// JitterSecondsLTE applies the LTE predicate on the "jitter_seconds" field.
func JitterSecondsLTE(v int) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldJitterSeconds, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotNull(FieldLastCheckedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.FieldLTE(FieldCreatedBy, v))
}

// HasChecks applies the HasEdge predicate on the "checks" edge.
func HasChecks() predicate.AccountMonitor {
	return predicate.AccountMonitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChecksTable, ChecksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChecksWith applies the HasEdge predicate on the "checks" edge with a given conditions (other predicates).
func HasChecksWith(preds ...predicate.AccountMonitorCheck) predicate.AccountMonitor {
	return predicate.AccountMonitor(func(s *sql.Selector) {
		step := newChecksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountMonitor {
	return predicate.AccountMonitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountMonitor {
	return predicate.AccountMonitor(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountMonitor) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountMonitor) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountMonitor) predicate.AccountMonitor {
	return predicate.AccountMonitor(sql.NotPredicates(p))
}
